name: xz_utils
version: 5.2.4

scheme:
  shared:
    options:
      shared: true
  static:
    options:
      shared: false
  
build-tools:
  msys2:
    version: 20200517
    if: compiler == 'Visual Studio'  

test:
  test_package:
    project: test_package

