name: m4
version: 1.4.18

build-tools:
  msys2: &MSYS2
    version: 20200517
    if: os == Windows

test:
  test:
    project: test_package
    program: false
    build-tools:
      msys2: *MSYS2
      m4: ${__version__}
