name: pkgconf
version: 1.7.3

program:
- name: test_package
  location: test_package
  executable: bin/test_package
  build-tools:
    pkgconf: ${__version__}
    msys2:
      version: 20200517
      if: os == Windows

build-tools:
  meson: 0.56.2
  automake: 1.16.2