name: pkgconf
version: 1.7.3


build-tools:
  meson: 0.57.1
  automake: 1.16.2


test:
  test_package:
    project: test_package
    build-tools:
      pkgconf: ${__version__}
      msys2:
        version: 20200517
        if: os == Windows
      automake: 1.16.2
