generate:
  stage: init
  tags:
  - ci-config-generator
  script: 
  - python .toolkit/bundle/main.py ci.gitlab.generate
  artifacts:
    paths:
      - .gitlab-ci/*.yml
trigger:
  stage: data
  trigger:
    include:
      - artifact: .gitlab-ci/data.yml
        job: generate
    strategy: depend
