stages:
  - init
  - data
generate:
  stage: init
  tags:
    - docker
    - gitlab-ci.config.generator
  script: 
  - echo python .toolkit/bundle/main.py ci.gitlab.generate
  artifacts:
    paths:
      - .gitlab-ci/*.yml
trigger:
  stage: data
  trigger:
    include:
      - artifact: .gitlab-ci/data.yml
        job: generate
    strategy: depend
