#stages:
#  - build
#build:
#  stage: build
#  tags:
#    - Linux
#    - docker
#    - builder
#    - workbench:oss-0.2
#  image: edgetoolkit/gcc6
#  script:
#    - cd zlib
#    - epm --profile gcc6 create

stages:
  - init
  - tools
  - packages
#
init:
  stage: init
  tags:
    - Linux
    - docker
    - runner
    - workbench:oss-0.2
  image: edgetoolkit/gcc5
  script:    
    - Install pip install networkx
    # python-gitlab --user
    - .gitlab-ci/bin/generate --trigger
  artifacts:
    paths:
    - .gitlab-ci/.cache/tools.yml
    - .gitlab-ci/.cache/packages.yml
#  rules:
#    - if: '$CI_COMMIT_BRANCH =~ /^RC\//'
#
tools:
  stage: tools
  trigger:
    include:
      - artifact: .gitlab-ci/.cache/tools.yml
        job: init
    strategy: depend
  rules:
  - if: '$CI_COMMIT_BRANCH =~ /^tool\//'
  - if: '$CI_TARGET == "tool"'
    when: manual

#
#
packages:
  stage: packages
  trigger:
    include:
      - artifact: .gitlab-ci/.cache/packages.yml
        job: init
    strategy: depend
  rules:
  - if: '$CI_TARGET == "package"'
    when: manual
  - if: '$CI_COMMIT_BRANCH =~ /^release\// || $CI_COMMIT_BRANCH == "testing" || $CI_COMMIT_BRANCH'
