stages:
  - startup
  - init

startup:
  stage: startup
  tags:
    - docker
    - gitlab-ci.config.generator
  script: 
  - echo python .toolkit/bin/gitlab-ci generate
  artifacts:
    paths:
      - .gitlab-ci/cache/trigger.yml
init:
  stage: init
  trigger:
    include:
      - artifact: .gitlab-ci/cache/trigger.yml
        job: startup
    strategy: depend
