stages:
  - init
  - tools
  - packages
#
init:
  stage: init
  tags:
    - Linux
    - docker
    - runner
    - workbench:Z1
  image: edgetoolkit/gcc5
  script:    
    - Install pip install networkx
    # python-gitlab --user
    - .gitlab-ci/script/generate --trigger
  artifacts:
    paths:
    - .gitlab-ci/.cache/tools.yml
    - .gitlab-ci/.cache/packages.yml
  rules:
  - if: '$CI_TARGET == "package" || $CI_TARGET == "tool"'
    when: manual
  - if: '$CI_COMMIT_BRANCH =~ /^release\//'
  - if: '$CI_COMMIT_BRANCH =~ /^tool\//'
  - changes: &_PACKAGEs
    - brotli/*
    - expat/*
    - sqlite3/*
    - libcurl/*
    - libwebsockets/*
    - mosquitto/*
    - zlib/*
    - openssl/*    

tools:
  stage: tools
  trigger:
    include:
      - artifact: .gitlab-ci/.cache/tools.yml
        job: init
    strategy: depend
  rules:
  - if: '$CI_COMMIT_BRANCH =~ /^tool\//'
  - if: '$CI_TARGET == "tool"'
    when: manual

packages:
  stage: packages
  trigger:
    include:
      - artifact: .gitlab-ci/.cache/packages.yml
        job: init
    strategy: depend
  rules:
  - if: '$CI_TARGET == "package"'
    when: manual
  - if: '$CI_COMMIT_BRANCH =~ /^release\//'
  - changes: *_PACKAGEs
    

# test tool 1


