stages:
  - startup
  - init

startup:
  stage: startup
  tags:
    - gitlab-ci.config.generator
  script:
    - pip install networkx python-gitlab
    - .toolkit/bin/gitlab-ci generate
  artifacts:
    paths:
      - .gitlab-ci/cache/trigger.yml
init:
  stage: init
#  tags:
#    - gitlab-ci.config.generator
  trigger:
    include:
      - artifact: .gitlab-ci/cache/trigger.yml
        job: startup
    strategy: depend
