#stages:
#  - startup
#  - init

#startup:
#  stage: startup
#  tags:
#    - gitlab-ci.config.generator
#  script:
#    - pip install networkx python-gitlab
#    - .toolkit/bin/gitlab-ci generate
#  artifacts:
#    paths:
#      - .gitlab-ci/.cache/trigger.yml
#init:
#  stage: init
#  trigger:
#    include:
#      - artifact: .gitlab-ci/.cache/trigger.yml
#        job: startup
#    strategy: depend
build.Linux:
  tags:
    - Linux
    - '@oss-0.1'
    - builder
  script:    
    - which python
    - pip list
build.Win:
  tags:
    - Windows
    - '@oss-0.1'
    - MSVC
    - builder
  script:    
    - echo $env:PATH
    - cmd.exe /c "where python"
    - cmd.exe /c "where pip"
    - pip list
    - python -c "import os; print(os.path.expanduser('~'));"


