stages:
  - startup
  - packages

startup:
  stage: startup
  tags:
    - gitlab-ci.config.generator
  script:
    - pip install networkx python-gitlab --user
    - .gitlab-ci/bin/generate --trigger
  artifacts:
    paths:
      - .gitlab-ci/.cache/trigger.yml
init:
  stage: packages
  trigger:
    include:
      - artifact: .gitlab-ci/.cache/trigger.yml
        job: startup
    strategy: depend
