stages:
  - trigger
  - tools
  - packages

startup:
  stage: trigger
  tags:
    - gitlab-ci.config.generator
  script:
    - pip install networkx python-gitlab --user
    - .gitlab-ci/bin/generate --trigger
  artifacts:
    paths:
      - .gitlab-ci/.cache/trigger.yml

tools:
  stage: tools
  trigger:
    include:
      - artifact: .gitlab-ci/.cache/tools.yml
        job: startup
    strategy: depend

packages:
  stage: packages
  trigger:
    include:
      - artifact: .gitlab-ci/.cache/packages.yml
        job: startup
    strategy: depend
