name: gstreamer
version: 1.18.4

build-tools:
  meson: 0.57.1
  pkgconf: 1.7.3

  winflexbison:
    version: 2.5.22
    if: compiler == 'Visual Studio'

  bison:
    version: 3.7.1
    if: compiler != 'Visual Studio'
  flex:
    version: 2.6.4
    if: compiler != 'Visual Studio'
#  glib: 2.68.1


dependencies:
  glib: 2.68.1
    
test:
  test_package:
    project: test_package

# CI 2