name: ninja
version: 1.10.2

build-tools:
  re2c: 1.3

test:
  test_package:
    project: test_package
    program: false
    build-tools:
      ninja: ${__version__}
  ninja:
    program: ninja

