name: ninja
version: 1.10.2

program:
- name: ninja
  executable: bin/ninja

- name: test
  location: test_package
  executable: false
  build-tools:
    ninja: ${__version__}

build-tools:
  re2c: 1.3
