name: expat
version: 2.3.0


scheme:
  shared:
    options:
      shared: true
  static:
    options:
      shared: false

program:
- name: test_package
  location: test_package
  executable: bin/test_package