stages:
- build
- deploy

    # ---------------------------------
    #     Build
    # ---------------------------------
7zip.build@windows:
    stage: build
    tags:
    - builder
    - Windows
    - '@oss-0.1'
    artifacts:
      paths:
      - 7zip/.conan/$PROFILE/$SCHEME
      - 7zip/.epm
    script:
    - cd 7zip
    - epm --profile $PROFILE --scheme $SCHEME  create --archive .conan/$PROFILE/$SCHEME
    parallel:
      matrix:
      - SCHEME: ['None']
        PROFILE: ['vs2019']

    # ---------------------------------
    #     deploy
    # ---------------------------------
7zip.publish@linux:
    stage: deploy
    tags:
    - '@oss-0.1'    
    - deployer
    script:
    - cd 7zip
    - epm --profile $PROFILE --scheme $SCHEME  --storage .conan/$PROFILE/$SCHEME upload
    parallel:
      matrix:
      - SCHEME: ['None']
        PROFILE: ['vs2019']
