- version: 0.2
  workbench: Z1
  # ====================================
  # TOOL PROFILE 
  # ====================================
  _profile.tool: &profile_tool
  - gcc5
  - vs2019
  _tool_setting: &tool_setting
    profile: *profile_tool
    tool: true
  # ====================================
  # PACKAGE PROFILE DEFINATION 
  # ====================================
  _profile.msvc: &profile_msvc
  - vs20{19}
  - vs20{19}d
  _profile.gcc: &profile_amd64
  - gcc{5|5d}
  _profile.arm: &profile_arm
  - gcc{5}-armv7
  - gcc{5}-armv7d
  _profile.arm: &profile_arm64
  - gcc{5}-armv8
  - gcc{5}-armv8d

  profile:
  - *profile_msvc
  - *profile_amd64
  - *profile_arm
  - *profile_arm64

# ======================================
# TOOL PACKAGE SETTING definations 
# ======================================
#- name: msys2
#  profile: vs2019
#  repack: true
#
#- name: strawberryperl
#  profile: vs2019
#  repack: true
#   
#- name: 7zip
#  profile: vs2019
#  tool: true
- name: winflexbison
  profile: vs2019
  tool: true
- name: bison
  profile: gcc5
  tool: true
- name: flex
  profile: gcc5
  tool: true
- name: pkgconf
  <<: *tool_setting
- name: m4
  <<: *tool_setting
- name: autoconf
  <<: *tool_setting
- name: automake
  <<: *tool_setting
- name: libtool
  <<: *tool_setting
- name: re2c
  <<: *tool_setting
- name: ninja
  <<: *tool_setting
- name: meson
  <<: *tool_setting
- name: nasm
  <<: *tool_setting
   
- zlib
- brotli
- name: bzip2
  program: test_package --help
- expat
- openssl
- name: pcre
  program:
    Windows: test_package "\w+ Bincrafters"
    Linux: test_package "\\w+ Bincrafters"
- name: pthreads4w
  profile: *profile_msvc
- sqlite3
#- gtest
- libiconv
- xz_utils
#- protobuf
#- name: protoc
#  <<: *tool_setting
- libcurl
- libwebsockets
- mosquitto
#- c-ares
#- name: iperf
#  -profile: *profile_msvc
