stages:
- build
- deploy

    # ---------------------------------
    #     Build
    # ---------------------------------
nasm.build@windows:
    stage: build
    tags:
    - builder
    - Windows
    - '@oss-0.1'
    artifacts:
      paths:
      - nasm/.conan/$PROFILE/$SCHEME
      - nasm/.epm
    script:
    - cd nasm
    - echo epm --profile $PROFILE --scheme $SCHEME  create --archive .conan/$PROFILE/$SCHEME
    parallel:
      matrix:
      - SCHEME: ['None']
        PROFILE: ['vs2019']

nasm.build@linux:
    stage: build
    tags:
    - builder
    - Linux
    - '@oss-0.1'
    artifacts:
      paths:
      - nasm/.conan/$PROFILE/$SCHEME
      - nasm/.epm
    script:
    - cd nasm
    - echo epm --profile $PROFILE --scheme $SCHEME  create --archive .conan/$PROFILE/$SCHEME
    parallel:
      matrix:
      - SCHEME: ['None']
        PROFILE: ['gcc5']
    


    # ---------------------------------
    #     deploy
    # ---------------------------------
nasm.publish@linux:
    stage: deploy
    tags:
    - '@oss-0.1'    
    - deployer
    script:
    - cd nasm
    - echo epm --profile $PROFILE --scheme $SCHEME  --storage .conan/$PROFILE/$SCHEME upload
    parallel:
      matrix:
      - SCHEME: ['None']
        PROFILE: ['vs2019']

      - SCHEME: ['None']
        PROFILE: ['gcc5']
