stages:
- build
- test
- deploy

    # ---------------------------------
    #     Build
    # ---------------------------------
openssl.build@windows:
    stage: build
    tags:
    - builder
    - Windows
    - '@oss-0.1'
    artifacts:
      paths:
      - openssl/.conan/$PROFILE/$SCHEME
      - openssl/.epm
    script:
    - cd openssl
    - echo epm --profile $PROFILE --scheme $SCHEME  create --archive .conan/$PROFILE/$SCHEME
    parallel:
      matrix:
      - SCHEME: ['static', 'shared']
        PROFILE: ['vs2019', 'vs2019d']

openssl.build@linux:
    stage: build
    tags:
    - builder
    - Linux
    - '@oss-0.1'
    artifacts:
      paths:
      - openssl/.conan/$PROFILE/$SCHEME
      - openssl/.epm
    script:
    - cd openssl
    - echo epm --profile $PROFILE --scheme $SCHEME  create --archive .conan/$PROFILE/$SCHEME
    parallel:
      matrix:
      - SCHEME: ['static', 'shared']
        PROFILE: ['gcc6d', 'gcc6', 'gcc8d', 'gcc8', 'gcc7d', 'gcc7', 'gcc5d', 'gcc5']

      - SCHEME: ['static', 'shared']
        PROFILE: ['gcc8-armv8d', 'gcc7-armv8d', 'gcc5-armv8', 'gcc6-armv8', 'gcc8-armv8', 'gcc7-armv8', 'gcc5-armv8d', 'gcc6-armv8d']
# ---------------------------------
    # Test
    # ---------------------------------

openssl.test@windows:
    stage: test
    tags:
    - runner
    - Windows
    - '@oss-0.1'
    script:
    - cd openssl
    - echo epm --profile $PROFILE --scheme $SCHEME  --storage .conan/$PROFILE/$SCHEME exec test_package
    parallel:
      matrix:
      - SCHEME: ['static', 'shared']
        PROFILE: ['vs2019', 'vs2019d']

openssl.test@linux:
    stage: test
    tags:
    - runner
    - Linux
    - '@oss-0.1'
    script:
    - cd openssl
    - echo epm --profile $PROFILE --scheme $SCHEME  --storage .conan/$PROFILE/$SCHEME exec test_package
    parallel:
      matrix:
      - SCHEME: ['static', 'shared']
        PROFILE: ['gcc6d', 'gcc6', 'gcc8d', 'gcc8', 'gcc7d', 'gcc7', 'gcc5d', 'gcc5']


    


    # ---------------------------------
    #     deploy
    # ---------------------------------
openssl.publish@linux:
    stage: deploy
    tags:
    - '@oss-0.1'    
    - deployer
    script:
    - cd openssl
    - echo epm --profile $PROFILE --scheme $SCHEME  --storage .conan/$PROFILE/$SCHEME upload
    parallel:
      matrix:
      - SCHEME: ['static', 'shared']
        PROFILE: ['vs2019', 'vs2019d']

      - SCHEME: ['static', 'shared']
        PROFILE: ['gcc6d', 'gcc6', 'gcc8d', 'gcc8', 'gcc7d', 'gcc7', 'gcc5d', 'gcc5']

      - SCHEME: ['static', 'shared']
        PROFILE: ['gcc8-armv8d', 'gcc7-armv8d', 'gcc5-armv8', 'gcc6-armv8', 'gcc8-armv8', 'gcc7-armv8', 'gcc5-armv8d', 'gcc6-armv8d']
