stages:
- build
- test
- deploy

    # ---------------------------------
    #     Build
    # ---------------------------------
pcre.build@windows:
    stage: build
    tags:
    - builder
    - Windows
    - '@oss-0.1'
    artifacts:
      paths:
      - pcre/.conan/$PROFILE/$SCHEME
      - pcre/.epm
    script:
    - cd pcre
    - epm --profile $PROFILE --scheme $SCHEME  create --archive .conan/$PROFILE/$SCHEME
    parallel:
      matrix:
      - SCHEME: ['shared', 'static']
        PROFILE: ['vs2019']

pcre.build@linux:
    stage: build
    tags:
    - builder
    - Linux
    - '@oss-0.1'
    artifacts:
      paths:
      - pcre/.conan/$PROFILE/$SCHEME
      - pcre/.epm
    script:
    - cd pcre
    - epm --profile $PROFILE --scheme $SCHEME  create --archive .conan/$PROFILE/$SCHEME
    parallel:
      matrix:
      - SCHEME: ['shared', 'static']
        PROFILE: ['gcc5']

      - SCHEME: ['shared', 'static']
        PROFILE: ['gcc7-armv8']


    # ---------------------------------
    # Test
    # ---------------------------------


pcre.test@windows:
    stage: test
    tags:
    - runner
    - Windows
    - '@oss-0.1'
    script:
    - cd pcre
    
    - epm --profile $PROFILE --scheme $SCHEME  --storage .conan/$PROFILE/$SCHEME exec test_package "\w+ Bincrafters"
    
    parallel:
      matrix:
      - SCHEME: ['shared', 'static']
        PROFILE: ['vs2019']


pcre.test@linux:
    stage: test
    tags:
    - runner
    - Linux
    - '@oss-0.1'
    script:
    - cd pcre
    
    - epm --profile $PROFILE --scheme $SCHEME  --storage .conan/$PROFILE/$SCHEME exec test_package "\\w+ Bincrafters"
    
    parallel:
      matrix:
      - SCHEME: ['shared', 'static']
        PROFILE: ['gcc5']


    


    # ---------------------------------
    #     deploy
    # ---------------------------------
pcre.publish@linux:
    stage: deploy
    tags:
    - '@oss-0.1'    
    - deployer
    script:
    - cd pcre
    - epm --profile $PROFILE --scheme $SCHEME  --storage .conan/$PROFILE/$SCHEME upload
    parallel:
      matrix:
      - SCHEME: ['shared', 'static']
        PROFILE: ['vs2019']

      - SCHEME: ['shared', 'static']
        PROFILE: ['gcc5']

      - SCHEME: ['shared', 'static']
        PROFILE: ['gcc7-armv8']
