stages:
- build
- deploy

    # ---------------------------------
    #     Build
    # ---------------------------------
protobuf.build@windows:
    stage: build
    tags:
    - builder
    - Windows
    - '@oss-0.1'
    artifacts:
      paths:
      - protobuf/.conan/$PROFILE/$SCHEME
      - protobuf/.epm
    script:
    - cd protobuf
    - epm --profile $PROFILE --scheme $SCHEME  create --archive .conan/$PROFILE/$SCHEME
    parallel:
      matrix:
      - SCHEME: ['shared', 'static']
        PROFILE: ['vs2019']

protobuf.build@linux:
    stage: build
    tags:
    - builder
    - Linux
    - '@oss-0.1'
    artifacts:
      paths:
      - protobuf/.conan/$PROFILE/$SCHEME
      - protobuf/.epm
    script:
    - cd protobuf
    - epm --profile $PROFILE --scheme $SCHEME  create --archive .conan/$PROFILE/$SCHEME
    parallel:
      matrix:
      - SCHEME: ['shared', 'static']
        PROFILE: ['gcc5']

    # ---------------------------------
    #     deploy
    # ---------------------------------
protobuf.publish@linux:
    stage: deploy
    tags:
    - '@oss-0.1'    
    - deployer
    script:
    - cd protobuf
    - epm --profile $PROFILE --scheme $SCHEME  --storage .conan/$PROFILE/$SCHEME upload
    parallel:
      matrix:
      - SCHEME: ['shared', 'static']
        PROFILE: ['vs2019']

      - SCHEME: ['shared', 'static']
        PROFILE: ['gcc5']
