stages:
- build
- test
- deploy

    # ---------------------------------
    #     Build
    # ---------------------------------
pthreads4w.build@windows:
    stage: build
    tags:
    - builder
    - Windows
    - '@oss-0.1'
    artifacts:
      paths:
      - pthreads4w/.conan/$PROFILE/$SCHEME
      - pthreads4w/.epm
    script:
    - cd pthreads4w
    - echo epm --profile $PROFILE --scheme $SCHEME  create --archive .conan/$PROFILE/$SCHEME
    parallel:
      matrix:
      - SCHEME: ['static', 'shared']
        PROFILE: ['vs2019']
# ---------------------------------
    # Test
    # ---------------------------------

pthreads4w.test@windows:
    stage: test
    tags:
    - runner
    - Windows
    - '@oss-0.1'
    script:
    - cd pthreads4w
    - echo epm --profile $PROFILE --scheme $SCHEME  --storage .conan/$PROFILE/$SCHEME exec test_package
    parallel:
      matrix:
      - SCHEME: ['static', 'shared']
        PROFILE: ['vs2019']


    


    # ---------------------------------
    #     deploy
    # ---------------------------------
pthreads4w.publish@linux:
    stage: deploy
    tags:
    - '@oss-0.1'    
    - deployer
    script:
    - cd pthreads4w
    - echo epm --profile $PROFILE --scheme $SCHEME  --storage .conan/$PROFILE/$SCHEME upload
    parallel:
      matrix:
      - SCHEME: ['static', 'shared']
        PROFILE: ['vs2019']
