stages:
- build
- deploy

    # ---------------------------------
    #     Build
    # ---------------------------------
re2c.build@windows:
    stage: build
    tags:
    - builder
    - Windows
    - '@oss-0.1'
    artifacts:
      paths:
      - re2c/.conan/$PROFILE/$SCHEME
      - re2c/.epm
    script:
    - cd re2c
    - epm --profile $PROFILE --scheme $SCHEME  create --archive .conan/$PROFILE/$SCHEME
    parallel:
      matrix:
      - SCHEME: ['None']
        PROFILE: ['vs2019']

re2c.build@linux:
    stage: build
    tags:
    - builder
    - Linux
    - '@oss-0.1'
    artifacts:
      paths:
      - re2c/.conan/$PROFILE/$SCHEME
      - re2c/.epm
    script:
    - cd re2c
    - epm --profile $PROFILE --scheme $SCHEME  create --archive .conan/$PROFILE/$SCHEME
    parallel:
      matrix:
      - SCHEME: ['None']
        PROFILE: ['gcc5']
    


    # ---------------------------------
    #     deploy
    # ---------------------------------
re2c.publish@linux:
    stage: deploy
    tags:
    - '@oss-0.1'    
    - deployer
    script:
    - cd re2c
    - epm --profile $PROFILE --scheme $SCHEME  --storage .conan/$PROFILE/$SCHEME upload
    parallel:
      matrix:
      - SCHEME: ['None']
        PROFILE: ['vs2019']

      - SCHEME: ['None']
        PROFILE: ['gcc5']
