stages:
- build
- test
- deploy

    # ---------------------------------
    #     Build
    # ---------------------------------
sqlite3.build@windows:
    stage: build
    tags:
    - builder
    - Windows
    - '@oss-0.1'
    artifacts:
      paths:
      - sqlite3/.conan/$PROFILE/$SCHEME
      - sqlite3/.epm
    script:
    - cd sqlite3
    - epm --profile $PROFILE --scheme $SCHEME  create --archive .conan/$PROFILE/$SCHEME
    parallel:
      matrix:
      - SCHEME: ['static', 'shared']
        PROFILE: ['vs2019']

sqlite3.build@linux:
    stage: build
    tags:
    - builder
    - Linux
    - '@oss-0.1'
    artifacts:
      paths:
      - sqlite3/.conan/$PROFILE/$SCHEME
      - sqlite3/.epm
    script:
    - cd sqlite3
    - epm --profile $PROFILE --scheme $SCHEME  create --archive .conan/$PROFILE/$SCHEME
    parallel:
      matrix:
      - SCHEME: ['static', 'shared']
        PROFILE: ['gcc5']

      - SCHEME: ['static', 'shared']
        PROFILE: ['gcc7-armv8']


    # ---------------------------------
    # Test
    # ---------------------------------


sqlite3.test@windows:
    stage: test
    tags:
    - runner
    - Windows
    - '@oss-0.1'
    script:
    - cd sqlite3
    
    - epm --profile $PROFILE --scheme $SCHEME  --storage .conan/$PROFILE/$SCHEME exec test_package
    
    parallel:
      matrix:
      - SCHEME: ['static', 'shared']
        PROFILE: ['vs2019']


sqlite3.test@linux:
    stage: test
    tags:
    - runner
    - Linux
    - '@oss-0.1'
    script:
    - cd sqlite3
    
    - epm --profile $PROFILE --scheme $SCHEME  --storage .conan/$PROFILE/$SCHEME exec test_package
    
    parallel:
      matrix:
      - SCHEME: ['static', 'shared']
        PROFILE: ['gcc5']


    


    # ---------------------------------
    #     deploy
    # ---------------------------------
sqlite3.publish@linux:
    stage: deploy
    tags:
    - '@oss-0.1'    
    - deployer
    script:
    - cd sqlite3
    - epm --profile $PROFILE --scheme $SCHEME  --storage .conan/$PROFILE/$SCHEME upload
    parallel:
      matrix:
      - SCHEME: ['static', 'shared']
        PROFILE: ['vs2019']

      - SCHEME: ['static', 'shared']
        PROFILE: ['gcc5']

      - SCHEME: ['static', 'shared']
        PROFILE: ['gcc7-armv8']
