stages:
- build
- test
- deploy

    # ---------------------------------
    #     Build
    # ---------------------------------
zlib.build@windows:
    stage: build
    tags:
    - builder
    - Windows
    - '@oss-0.1'
    artifacts:
      paths:
      - zlib/.conan/$PROFILE/$SCHEME
      - zlib/.epm
    script:
    - cd zlib
    - epm --profile $PROFILE --scheme $SCHEME  create --archive .conan/$PROFILE/$SCHEME
    parallel:
      matrix:
      - SCHEME: ['static', 'shared']
        PROFILE: ['vs2019']

zlib.build@linux:
    stage: build
    tags:
    - builder
    - Linux
    - '@oss-0.1'
    artifacts:
      paths:
      - zlib/.conan/$PROFILE/$SCHEME
      - zlib/.epm
    script:
    - cd zlib
    - epm --profile $PROFILE --scheme $SCHEME  create --archive .conan/$PROFILE/$SCHEME
    parallel:
      matrix:
      - SCHEME: ['static', 'shared']
        PROFILE: ['gcc5']

      - SCHEME: ['static', 'shared']
        PROFILE: ['gcc7-armv8']


    # ---------------------------------
    # Test
    # ---------------------------------


zlib.test@windows:
    stage: test
    tags:
    - runner
    - Windows
    - '@oss-0.1'
    script:
    - cd zlib
    
    - epm --profile $PROFILE --scheme $SCHEME  --storage .conan/$PROFILE/$SCHEME exec test_package
    
    parallel:
      matrix:
      - SCHEME: ['static', 'shared']
        PROFILE: ['vs2019']


zlib.test@linux:
    stage: test
    tags:
    - runner
    - Linux
    - '@oss-0.1'
    script:
    - cd zlib
    
    - epm --profile $PROFILE --scheme $SCHEME  --storage .conan/$PROFILE/$SCHEME exec test_package
    
    parallel:
      matrix:
      - SCHEME: ['static', 'shared']
        PROFILE: ['gcc5']


    


    # ---------------------------------
    #     deploy
    # ---------------------------------
zlib.publish@linux:
    stage: deploy
    tags:
    - '@oss-0.1'    
    - deployer
    script:
    - cd zlib
    - epm --profile $PROFILE --scheme $SCHEME  --storage .conan/$PROFILE/$SCHEME upload
    parallel:
      matrix:
      - SCHEME: ['static', 'shared']
        PROFILE: ['vs2019']

      - SCHEME: ['static', 'shared']
        PROFILE: ['gcc5']

      - SCHEME: ['static', 'shared']
        PROFILE: ['gcc7-armv8']
