stages:
- build
- test
- deploy

    # ---------------------------------
    #     Build
    # ---------------------------------
#zlib.build@msvc:
#    stage: build
#    tags:
#    - builder
#    - Windows
#    - '@oss-0.1'
#    artifacts:
#      paths:
#      - zlib/.conan/$PROFILE/$SCHEME
#      - zlib/.epm
#    script:
#    - cd zlib
#    - echo epm --profile $PROFILE --scheme $SCHEME  create --archive .conan/$PROFILE/$SCHEME
#    parallel:
#      matrix:
#      - SCHEME: ['static', 'shared']
#        PROFILE: ['vs2019']

zlib.build@gcc5:
    stage: build
    tags:
    - Linux  
    - builder
    - docker
    - 'workbench:oss-0.2'
    image: edgetoolkit/gcc5
    artifacts:
      paths:
      - zlib/.conan/$PROFILE/$SCHEME
      - zlib/.epm
    script:
    - cd zlib
    - epm --profile $PROFILE --scheme $SCHEME  create --archive .conan/$PROFILE/$SCHEME --with-deps
    parallel:
      matrix:
      - SCHEME: ['static', 'shared']
        PROFILE: ['gcc5']


    # ---------------------------------
    # Test
    # ---------------------------------


#zlib.test@windows:
#    stage: test
#    tags:
#    - runner
#    - Windows
#    - '@oss-0.1'
#    script:
#    - cd zlib
#    
#    - epm --profile $PROFILE --scheme $SCHEME  --storage .conan/$PROFILE/$SCHEME exec test_package
#    
#    parallel:
#      matrix:
#      - SCHEME: ['static', 'shared']
#        PROFILE: ['vs2019']


zlib.test@gcc5:
    stage: test
    tags:
    - Linux  
    - runner
    - docker
    - 'workbench:oss-0.2'
    image: ubuntu:xenial
    dependencies:
    - zlib.build@gcc5
    script:
    - cd zlib    
    - echo epm --profile $PROFILE --scheme $SCHEME  --storage .conan/$PROFILE/$SCHEME exec test_package
    - export EPM_SANDBOX_STORAGE=.conan/$PROFILE/$SCHEME && ./.epm/$PROFILE@$SCHEME/program/test_package/run
    
    parallel:
      matrix:
      - SCHEME: ['static', 'shared']
        PROFILE: ['gcc5']


    


    # ---------------------------------
    #     deploy
    # ---------------------------------
zlib.deploy@linux:
    stage: deploy
    tags:
    - conan  
    - deployer
    - 'workbench:oss-0.2'
    dependencies:
    - zlib.build@gcc5
    script:
    - cd zlib
    - epm --profile $PROFILE --scheme $SCHEME  --storage .conan/$PROFILE/$SCHEME upload
    parallel:
      matrix:
#      - SCHEME: ['static', 'shared']
#        PROFILE: ['vs2019']

      - SCHEME: ['static', 'shared']
        PROFILE: ['gcc5']

#      - SCHEME: ['static', 'shared']
#        PROFILE: ['gcc7-armv8']
