name: automake
version: 1.16.2

build-tools:
  msys2: &MSYS2
    version: 20200517
    if: os == Windows

dependencies:
  autoconf:  2.69


program:
- name: test_package
  location: test_package
  executable: test_package
  build-tools:
    automake: ${__version__}
    msys2: *MSYS2
    
    