name: automake
version: 1.16.2

build-tools:
  msys2: &MSYS2
    version: 20200517
    if: os == Windows


dependencies:
  autoconf:  2.69


test:
  test_package:
    project: test_package
    program: test_package
    build-tools:
      automake: ${__version__}
      msys2: *MSYS2
