gitlab_runner_out_dir: "/tmp/ansible-gitlab-runner"
gitlab_runner_workbench: "oss-0.1"
gitlab_runner_conan_repo: "oss-0.1"
gitlab_runner_concurrency: 1
gitlab_runner_builder: 1
gitlab_runner_tester: 1
gitlab_runner_deployer: 0
gitlab_runner_ci_generator: 0



