name: libcurl
version: 7.75.0

scheme:
  shared:
    options:
      shared: true
      with_ssl: false
  static:
    options:
      shared: false


program:
- name: test_package
  location: test_package
  executable: bin/test_package

build-tools:
  libtool: 
    version: 2.4.6
    if: os != Windows
  pkgconf: 
    version: 1.7.3
    if: os != Windows
  
#  msys2:
#    version: 20200517
#    if: os == Windows


dependencies:
  zlib: 1.2.11
  openssl:
    version: 1.1.1i
    if: options.with_ssl == openssl


