#!/usr/bin/env bash
# GITLAB CI DEPLOYMENT TOOL WITH ANSIBLE
#
#
#
#
###########################################################
_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)
docker run -it --rm --name ansible-playbook \
       -v $PWD:/home/ansible/rolses \
       -w oss /home/ansible/rolses \
       --user $(id -u):$(id -g) edgetoolkit/ansible /bin/bash -c "ansible-playbook $*"

