- hosts: linux_server
  vars:
    - COMMAND: install
  roles:
  - role: sysconf
    when:
    - target == "sysconf"
- hosts: linux_server
  roles:
  - role: avanov.pyenv
    pyenv_path: "/home/{{ ansible_ssh_user }}/pyenv"
    pyenv_owner: "{{ ansible_ssh_user }}"
    pyenv_global: "3.6.5"
    pyenv_update_git_install: no
    pyenv_enable_autocompletion: no
    pyenv_python_versions:
      - "3.8.6"
#         - "3.4.1"
#         - "2.7.8"
    pyenv_virtualenvs:
    - venv_name: "latest_v3"
      py_version: "3.4.1"
    - venv_name: "latest_v2"
      py_version: "2.7.8"
    when:
    - target == "sysconf"

- hosts: artifactory
  vars:
    - COMMAND: install
  roles:
  - role: artifactory
    when:
    - target == "artifactory"
#    - inventory_hostname in groups['artifactory']
- hosts: nexus3
  vars:
    - COMMAND: install
  roles:
  - role: nexus3
    when:
    - target == "nexus3"

- hosts: gitlab
  vars:
    - COMMAND: install
  roles:
  - role: gitlab
    when:
    - target == "gitlab"

- hosts: gitlab_runner
  vars:
    - COMMAND: install
  roles:
  - role: gitlab-runner
    when:
    - target == "gitlab-runner"
#    - inventory_hostname in groups['gitlab']

