---

# 1. reset all configured hostname
# 2. generate gitlab config for each hostname
# 3. deploy configs

- name: update config in gitlab
  shell: |
    /oss/.toolkit/bin/gitlab-ci runner.reset --url {{GITLAB_URL}} \
      --token {{GITLAB_PRIVATE_TOKEN}} \
      --dir /oss/.toolkit/var/gitlab-runner \
      --hostname {{ansible_ssh_host}}

    rm -rf /oss/tmp/config
    /oss/.toolkit/bin/gitlab-ci runner.config --url {{GITLAB_URL}} \
      --token {{GITLAB_PRIVATE_TOKEN}} \
      --dir /oss/.toolkit/var/gitlab-runner \
      --hostname {{ansible_ssh_host}} \
      --builder {{GITLAB_RUNNER_BUILDER}}  \
      --tester {{GITLAB_RUNNER_TESTER}} \
      --deployer {{GITLAB_RUNNER_DEPLOYER}} \
      --trigger {{GITLAB_RUNNER_CI_GENERATOR}}   \
      --platform {{ansible_system}}      \
      --arch {{ansible_architecture}} \
      --workbench workbench=oss/{{OSS_VERSION}} \
      --out /oss/tmp/config
#  with_items: "{{ OSS_VERSIONS.split(',')}}"
  delegate_to: localhost