---

# 1. reset all configured hostname
# 2. generate gitlab config for each hostname
# 3. deploy configs

- name: update config in gitlab
  shell: |
    /oss/.toolkit/bin/gitlab-ci runner.reset --url {{GITLAB_URL}} \
      --token {{GITLAB_PRIVATE_TOKEN}} \
      --dir /oss/.toolkit/var/gitlab-runner \
      --hostname {{inventory_hostname}}

    /oss/.toolkit/bin/gitlab-ci runner.config --url {{GITLAB_URL}} \
      --token {{GITLAB_PRIVATE_TOKEN}} \
      --dir /oss/.toolkit/var/gitlab-runner
      --hostname {{inventory_hostname}}
      --builder {{GITLAB_RUNNER_BUILDER}}  \
      --tester {{GITLAB_RUNNER_TESTER}} \
      --deployer {{GITLAB_RUNNER_DEPLOYER}} \
      --trigger {{GITLAB_RUNNER_CI_GENERATOR}}   \
      --platform {{ansible_os_family}}      \
      --workbench workbench=oss/{{OSS_VERSION}}
#  with_items: "{{ OSS_VERSIONS.split(',')}}"
  delegate_to: localhost