---

# 1. reset all configured hostname
# 2. generate gitlab config for each hostname
# 3. deploy configs

- name: reset config in gitlab
  shell: |
    /oss/.toolkit/bin/gitlab-ci runner.reset --url {{GITLAB_URL}} \
      --token {{GITLAB_PRIVATE_TOKEN}} \
      --dir /oss/.toolkit/var/gitlab-runner \
      --hostname {{ansible_ssh_host}}
  delegate_to: localhost

- name: config in gitlab
  shell: |
    /oss/.toolkit/bin/gitlab-ci runner.config --url {{GITLAB_URL}} \
      --token {{GITLAB_PRIVATE_TOKEN}} \
      --dir /oss/.toolkit/var/gitlab-runner \
      --hostname {{ansible_ssh_host}} \
      --builder {{GITLAB_RUNNER_BUILDER}}  \
      --tester {{GITLAB_RUNNER_TESTER}} \
      --deployer {{GITLAB_RUNNER_DEPLOYER}} \
      --trigger {{GITLAB_RUNNER_CI_GENERATOR}}   \
      --platform {{ansible_system}}      \
      --arch {{ansible_architecture}} \
      --workbench workbench=oss/{{OSS_VERSION}}
  delegate_to: localhost

- name: generate runner config and workbench files
  shell: |
    /oss/.toolkit/bin/gitlab-ci runner.make --url {{GITLAB_URL}} \
      --token {{GITLAB_PRIVATE_TOKEN}} \
      --dir /oss/.toolkit/var/gitlab-runner \
      --hostname {{ansible_ssh_host}} \
      --out /oss/.tmp/gitlab-runner
  delegate_to: localhost