---
# https://blog.51cto.com/7424593/2174156
- name: Create epm home folder
  become: yes
  file:
    path: "C:/Users/{{ansible_ssh_user}}/.epm"
    state: directory
    mode: 0755
    recurse: yes

- name: Download gitlab-runner program to specified path
  win_get_url:
    url: "{{GITLAB_RUNNER_BINARY_REPO}}/binaries/gitlab-runner-windows-amd64.exe"
    dest: "C:/Users/{{ansible_ssh_user}}/.epm/gitlab-runner.exe"