---
# https://blog.51cto.com/7424593/2174156
- name: Create epm home folder
  win_file:
    path: C:\Users\{{ansible_ssh_user}}\.epm
    state: directory

- name: Download gitlab-runner program to specified path
  win_get_url:
    url: "{{ARCHIVE_REPO_URL}}/gitlab-runner/v{{GITLAB_RUNNER_VERSION}}/binaries/gitlab-runner-windows-amd64.exe"
    dest: C:\Users\{{ansible_ssh_user}}\.epm\gitlab-runner.exe

- name: Download mirror.yml
  win_get_url:
    url: "{{ARCHIVE_REPO_URL}}/mirrors.yml"
    dest: C:\Users\{{ansible_ssh_user}}\.epm\mirrors.yml