- name: Register gitlab-runner
  gitlab_runner_register:
    hostname: "{{ansible_ssh_host}}"
    type: "{{item}}"
    config: "{{GITLAB_RUNNER_CONFIG_FILE}}"
    db: "{{GITLAB_RUNNER_REGISTER_DB}}"
  with_list: group_names

  delegate_to: localhost