name: mosquitto
version: 1.4.15

scheme:
  shared:
    options:
      shared: true
  static:
    options:
      shared: false

program:
- name: test_package
  location: test_package
  executable: bin/test_package

dependencies:
  openssl:
    version: 1.1.1g
    if: options.with_tls
  c-ares:
    version: 1.15.0
    if: options.with_srv   

