name: mosquitto
version: 2.0.7

scheme:
  shared:
    options:
      shared: true
  static:
    options:
      shared: false

dependencies:
  openssl:
    version: 1.1.1i
    if: options.ssl
  libwebsockets:
    version: 4.1.6
    if: options.with_websockets
       

test:
  test_package:
    project: test_package


# CI 2