
gitlab_runner:
  vars:
    gitlab_runner:
      version: 13.8.0
      url: http://172.16.0.121:8200
      token: kypLygrDSZ-92NewWx4R
      epm: git+http://172.16.0.121:8200/edgetoolkit/epm.git@dev/0.1

      mirror:
        repository: http://172.16.0.119/archive

      conan:
        name: oss-0.1
        url: http://172.16.0.119:8060/artifactory/api/conan/oss-0.1
        username: mingyiz
        password: Admin123

      runner:
        1: ufMfJ4NWCH2PFxuWgGpK
        2: C3WW6iywXxPtTMyNWztz
        3: VuQP2myicn1Z51y1CKiT
        4: s7bsC2xA8iXDKyhNweuT
        5: NNstKXyD7L97FEP8xR6t
        6: SCNgitytYLY8nTKzBsPg
        7: xroK_exgs7JQ6Njwjh_K
        8: sBgTyFv9bAb13b6kQCmW
        9: K_Ym7MsLV4o1yq9TVho7
        10: zzyE3L4FzszqrEhK4u3B
        11: EpsXGG_3xx9-AvQMQWkX
        12: bNWciMEoSfy4Q1EES7FG
        13: s-2LzpQTAjfnkNd4nxPh
        14: QxzbkvEsMuxBy-XcWbuP
        15: MHpr8sMhcpicR9DKS_MB
        16: sHNxMWmayRGt2rPVETfQ
        17: xfCHyw2Le-5shzfc-6Pg
        18: y8xT6JLmTb1XRLCGx8jz
        19: X6B9iV4zQqssUn4ymK-G
        20: PdWCoYezD-YRygBvF3Dt
        21: 8TsBr9Hfw49m38Ns3kNS
