
linux:
  hosts:
    server01:
      ansible_host: 172.16.0.119

    server02:
      ansible_host: 172.16.0.121

  vars:
    ansible_ssh_port=22
    ansible_ssh_user=edgetoolkit
    ansible_ssh_pass=edgetoolkit
    ansible_sudo_pass=edgetoolkit