---
- name: Create gitlab-runner and epm folders
  file:
    path: "{{ ansible_env.HOME }}/.gitlab-runner"
    state: directory
    mode: '0755'

- name: Download gitlab-runner program to ~/.gitlab-runner
  get_url:
    url: "{{mirror_repository_url | default('https://gitlab-runner-downloads.s3.amazonaws.com')}}/gitlab-runner/v{{gitlab_runner_version}}/binaries/gitlab-runner-linux-amd64"
    dest: /home/{{ansible_ssh_user}}/.gitlab-runner/gitlab-runner
    mode: '0766'

- name: Install gitlab service
  shell: |
    set +e
    ./gitlab-runner stop
    ./gitlab-runner uninstall
    set -e
    ./gitlab-runner install -c config.toml --user {{ansible_env.USER}}

  args:
    chdir: "{{ ansible_env.HOME }}/.gitlab-runner"
  become: yes
