- name: Stop gitlab service
  shell: |
    ./gitlab-runner stop
  args:
    chdir: "{{ ansible_env.HOME }}/.gitlab-runner"
  become: yes
  ignore_errors: yes

- name: Remove previous generated workbench
  file:
    path: "{{ ansible_env.HOME }}/.epm/.workbench/{{item['workbench']}}"
    state: absent
  with_list: "{{runners}}"
  when: item['kind'] != 'gitlab-ci.config.generator'

- name: Create workbench folders
  file:
    path: "{{ ansible_env.HOME }}/.epm/.workbench/{{item['workbench']}}/script"
    state: directory
    mode: '0744'
    recurse: yes
  with_list: "{{runners}}"
  when: item['kind'] != 'gitlab-ci.config.generator'

- name: copy workbench config file
  template:
    src: workbench/config.yml.j2
    dest: "{{ ansible_env.HOME }}/.epm/.workbench/{{item['workbench']}}/config.yml"
  with_list: "{{runners}}"
  when: item['kind'] != 'gitlab-ci.config.generator'

- name: Initialize workbench
  shell: |
    kind={{item['kind']}}
    WD={{ ansible_env.HOME }}/.epm/.workbench/{{item['workbench']}}
    source ~/.pyenv/.pyenvrc
    python -m venv $WD/venv
    source $WD/venv/bin/activate
    pip config set global.index-url http://172.16.0.121:8040/repository/pypi/simple
    pip config set install.trusted-host 172.16.0.121
    pip install --upgrade pip
    [[ $kind == "deployer" ]] && echo YES
    [[ $kind == "deployer" ]] || echo NO
    pip install {{gitlab_runner_epm | default('-e ~/editable/epm')}}
    export CONAN_USER_HOME=$WD
    export CONAN_REVISIONS_ENABLED=1
    conan remote clean
    conan remote add {{gitlab_runner.conan.name}} {{gitlab_runner.conan.url}} False
    if [[ $kind == "deployer" ]]; then
      conan user -p {{gitlab_runner.conan.password}} -r {{gitlab_runner.conan.name}} {{gitlab_runner.conan.username}}
    fi
  args:
    executable: /bin/bash  
  with_list: "{{runners}}"
  when: 
  - item['kind'] != 'gitlab-ci.config.generator'

- name: generate runner pre_build.py
  template:
    src: workbench/script/{{item['kind']}}-pre_build.py.j2
    dest: "{{ansible_env.HOME}}/.epm/.workbench/{{item['workbench']}}/script/pre_build.py"
  with_list: "{{runners}}"
  when: item['kind'] != 'gitlab-ci.config.generator'

- name: Copy mirrors.yml
  get_url:
    url: "{{mirror_repository_url}}/mirrors.yml"
    dest: "{{ ansible_env.HOME }}/.epm/mirrors.yml"

- name: Startup service
  shell: |
    ./gitlab-runner start
  args:
    chdir: "{{ ansible_env.HOME }}/.gitlab-runner"
  become: yes
