name: protobuf
version: 3.15.5

scheme:
  shared:
    options:
      shared: true
  static:
    options:
      shared: false

#program:
#- name: test_package
#  location: test_package
#  executable: bin/test_package

build-tools:
  protoc:
    version: ${__version__}
    if: cross_build

dependencies:
  zlib: 
    version: 1.2.11
    if: options.with_zlib
#####

