name: libtool
version: 2.4.6

dependencies:
    automake: 1.16.2

build-tools:
    msys2: &MSYS2
        version: 20200517
        if: os == Windows


test:
  test_package:
    project: test_package
    build-tools:
      libtool: ${__version__}
      msys2: *MSYS2