name: libtool
version: 2.4.6

program:
- name: test_package
  location: test_package
  executable: bin/test_package
  build-tools:
    libtool: ${__version__}
build-tools:
    msys2:
        version: 20200517
        if: os == Windows

dependencies:
    automake: 1.16.2
