---
- name: Config gitlab service runner for {{ansible_ssh_host}}
  gitlab_runner_command:
    command: configure
    db: "{{gitlab_runner}}" 
    hostname: "{{ansible_ssh_host}}"
    builder: "{{gitlab_runner_builder}}"
    runner: "{{gitlab_runner_runner}}"
    deployer: "{{gitlab_runner_deployer}}"
    trigger: "{{gitlab_runner_ci_generator}}"
    workbench: "{{gitlab_runner.workbench}}"
    platform: "{{'Windows' if ansible_system == 'Win32NT' else ansible_system}}"
    arch: "{{ansible_architecture2 if ansible_system == 'Win32NT' else ansible_architecture}}"
  delegate_to: localhost
  register: result

- name: set_fact
  set_fact:
    runners: "{{ result.runners }}"

- name: Apply gitlab-runner config.toml
  template:
    src: config.toml.j2
    dest: "{{ ansible_env.USERPROFILE if ansible_system.startswith('Win') else ansible_env.HOME }}/.gitlab-runner/config.toml"

