- name: S
  win_shell: |
    echo A
    $_HOME = "{{ansible_env.USERPROFILE | regex_replace('\\', '/')}}"
    $_X = "$_HOME"
    echo "$_X"
    echo "$_HOME"

  register: result
#  args:
#    executable: /bin/bash


- name: Y
  debug:
    msg: "{{result}}"
