- name: Inspect gitlab-runner instance info
  gitlab_runner_command:
    command: info
    db: "{{gitlab_runner}}" 
    hostname: "{{ansible_ssh_host}}"
  delegate_to: localhost
  register: result
- name: XX
  debug:
    msg: "{{result}}"

- name: set_fact
  set_fact:
    runners: "{{ result.runners }}"
- name: X
  debug:
    msg: "{{item['workbench']}} {{item['hostname']}}"
  with_list: "{{runners}}"

