- name: Stop service before deploy workbench
  win_shell: |
    ./gitlab-runner stop
  args:
    chdir: "{{ ansible_env.USERPROFILE }}/.gitlab-runner"
    executable: powershell
  ignore_errors: yes

- name: Remove previous generated workbench
  win_file:
    path: "{{ ansible_env.USERPROFILE }}/.epm/.workbench/{{item['workbench']}}"
    state: absent
  with_list: "{{runners}}"
  when: item['kind'] != 'gitlab-ci.config.generator'

- name: Copy mirrors.yml
  win_get_url:
    url: "{{mirror_repository_url}}/mirrors.yml"
    dest: "{{ ansible_env.USERPROFILE }}/.epm/mirrors.yml"
  when: 
  - mirror_repository_url is defined

- name: Create workbench folders (windows)
  win_file:
    path: "{{ ansible_env.USERPROFILE }}/.epm/.workbench/{{item['workbench']}}/script"
    state: directory
    recurse: yes
  with_list: "{{runners}}"
  when: item['kind'] != 'gitlab-ci.config.generator'

- name: copy workbench config file (windows) 
  template:
    src: workbench/config.yml.j2
    dest: "{{ ansible_env.USERPROFILE }}/.epm/.workbench/{{item['workbench']}}/config.yml"
  with_list: "{{runners}}"
  when: item['kind'] != 'gitlab-ci.config.generator'

- name: Initialize workbench (windows)
  win_shell: |
    $kind = "{{item['kind']}}"
    $WD = "{{ansible_env.USERPROFILE | regex_replace('\\', '/')}}/.epm/.workbench/{{item['workbench']}}"
    
    python -m venv $WD/venv
    . $WD/venv/Scripts/Activate.ps1
    cmd.exe /c "where pip"
    python -m pip config set global.index-url http://172.16.0.121:8040/repository/pypi/simple
    python -m pip config set install.trusted-host 172.16.0.121
    python -m pip install --upgrade pip
    python -m pip install {{gitlab_runner_epm | default('-e c:/editable/epm')}}

    $env:CONAN_USER_HOME="$WD"
    $env:CONAN_REVISIONS_ENABLED="1"
    conan remote clean
    conan remote add {{gitlab_runner.conan.name}} {{gitlab_runner.conan.url}} False
    if( $kind -eq "deployer") {
      conan user -p {{gitlab_runner.conan.password}} -r {{gitlab_runner.conan.name}} {{gitlab_runner.conan.username}}
    }
  with_list: "{{runners}}"
  when: 
  - item['kind'] != 'gitlab-ci.config.generator'

- name: Copy runner pre_build
  template:
    src: workbench/script/{{item['kind']}}-pre_build.py.j2
    dest: "{{ansible_env.USERPROFILE}}/.epm/.workbench/{{item['workbench']}}/script/pre_build.py"
  with_list: "{{runners}}"
  when: item['kind'] != 'gitlab-ci.config.generator'

- name: Startup service
  win_shell: |
    ./gitlab-runner start
  args:
    chdir: "{{ ansible_env.USERPROFILE }}/.gitlab-runner"
    executable: powershell
