name: libwebsockets
version: 4.0.15

scheme:
  shared:
    options:
      shared: true
  static:
    options:
      shared: false

program:
- name: test_package
  location: test_package
  executable: bin/test_package

dependencies:
  openssl: 
    version: 1.1.1g
    if: options.with_ssl == openssl
  sqlite3:
    version: 3.32.3
    if: options.with_sqlite3
#