
stages:
- build
- deploy


    # =================================
    # MSVC build
    # =================================
7zip:MSVC@build:
  stage: build
  tags:
  - Windows
  - builder
  - workbench:oss-0.2
  artifacts:
    paths:
    - 7zip/.conan/$EPM_PROFILE/$EPM_SCHEME
    - 7zip/.epm
  script:
  - cd 7zip
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME
  parallel:
    matrix:
    - EPM_PROFILE: ['vs2019']
      EPM_SCHEME: ['None']

    # =================================
    # Deploy to conan repo
    # =================================
7zip@deploy:
  stage: deploy
  tags:
  - conan
  - deployer
  - workbench:oss-0.2
  dependencies:
  - 7zip:MSVC@build
  script: |
    set -e
    cd 7zip
    PROFILES=(
      vs2019
    )

    for profile in $PROFILES
    do
      for scheme in None
      do
        export EPM_PROFILE=$profile
        export EPM_FPROFILE=$scheme
        echo [7zip] - Upload...  $profile $shcme
        epm upload .conan/$profile/$scheme
      done
    done 