
stages:
- build
- deploy


    # =================================
    # MSVC build
    # =================================
autoconf:MSVC@build:
  stage: build
  tags:
  - Windows
  - builder
  - workbench:oss-0.2
  artifacts:
    paths:
    - autoconf/.conan/$EPM_PROFILE/$EPM_SCHEME
    - autoconf/.epm
  script:
  - cd autoconf
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME
  parallel:
    matrix:
    - EPM_PROFILE: ['vs2019']
      EPM_SCHEME: ['None']

    # =========================================
    # gcc5 x86_64 build
    # =========================================
autoconf:gcc5@build:
  stage: build
  tags:
  - Linux
  - builder
  - docker
  - workbench:oss-0.2
  image: 172.16.0.119:8482/edgetoolkit/gcc5
  artifacts:
    paths:
    - autoconf/.conan/$EPM_PROFILE/$EPM_SCHEME
    - autoconf/.epm
  script:
  - cd autoconf
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc5']
      EPM_SCHEME: ['None']

    # =================================
    # Deploy to conan repo
    # =================================
autoconf@deploy:
  stage: deploy
  tags:
  - conan
  - deployer
  - workbench:oss-0.2
  dependencies:
  - autoconf:gcc5@build
  - autoconf:MSVC@build
  script: |
    set -e
    cd autoconf
    PROFILES=(
      gcc5
      vs2019
    )

    for profile in $PROFILES
    do
      for scheme in None
      do
        export EPM_PROFILE=$profile
        export EPM_FPROFILE=$scheme
        echo [autoconf] - Upload...  $profile $shcme
        epm upload .conan/$porofile/$scheme
      done
    done 