
stages:
- build
- deploy


    # =================================
    # MSVC build
    # =================================
autoconf:MSVC@build:
  stage: build
  tags:
  - Windows
  - builder
  - workbench:Z1
  artifacts:
    paths:
    - autoconf/.conan/$EPM_PROFILE/$EPM_SCHEME
    - autoconf/.epm
  script:
  - cd autoconf
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME   --clear
  parallel:
    matrix:
    - EPM_PROFILE: ['vs2019']
      EPM_SCHEME: ['None']

    # =========================================
    # gcc5 x86_64 build
    # =========================================
autoconf:gcc5@build:
  stage: build
  tags:
  - Linux
  - builder
  - docker
  - workbench:Z1
  image: 172.16.0.119:8482/edgetoolkit/gcc5
  artifacts:
    paths:
    - autoconf/.conan/$EPM_PROFILE/$EPM_SCHEME
    - autoconf/.epm
  script:
  - cd autoconf
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME  --clear
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc5']
      EPM_SCHEME: ['None']

    # =================================
    # Deploy to conan repo
    # =================================
autoconf@deploy:
  stage: deploy
  tags:
  - conan
  - deployer
  - workbench:Z1

  image: 172.16.0.119:8482/edgetoolkit/gcc5

  dependencies:
  - autoconf:MSVC@build
  - autoconf:gcc5@build
  script:
  - epm -p vs2019 -s None upload --storage .conan/vs2019/None
  - epm -p gcc5 -s None upload --storage .conan/gcc5/None