
stages:
- build
- deploy



    # =========================================
    # gcc5 x86_64 build
    # =========================================
bison:gcc5@build:
  stage: build
  tags:
  - Linux
  - builder
  - docker
  - workbench:Z1
  image: edgetoolkit/gcc5
  artifacts:
    paths:
    - bison/.conan/$EPM_PROFILE/$EPM_SCHEME
    - bison/.epm
  script:
  - cd bison
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME  --clear
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc5']
      EPM_SCHEME: ['none']

    # =================================
    # Deploy to conan repo
    # =================================
bison@deploy:
  stage: deploy
  tags:
  - conan
  - deployer
  - workbench:Z1

  dependencies:
  - bison:gcc5@build
  script:
  - cd bison
  - epm -p gcc5 -s none upload --storage .conan/gcc5/none