
stages:
- build
- deploy



    # =========================================
    # gcc5 x86_64 build
    # =========================================
flex:gcc5@build:
  stage: build
  tags:
  - Linux
  - builder
  - docker
  - workbench:Z1
  image: 172.16.0.119:8482/edgetoolkit/gcc5
  artifacts:
    paths:
    - flex/.conan/$EPM_PROFILE/$EPM_SCHEME
    - flex/.epm
  script:
  - cd flex
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME  --clear
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc5']
      EPM_SCHEME: ['None']

    # =================================
    # Deploy to conan repo
    # =================================
flex@deploy:
  stage: deploy
  tags:
  - conan
  - deployer
  - workbench:Z1

  image: 172.16.0.119:8482/edgetoolkit/gcc5

  dependencies:
  - flex:gcc5@build
  script:
  - epm -p gcc5 -s None upload --storage .conan/gcc5/None