stages:
- build
- test
- deploy

    # =================================
    # MSVC build
    # =================================
libiconv:MSVC@build:
  stage: build
  tags:
  - Windows
  - builder
  - workbench:oss-0.2
  artifacts:
    paths:
    - libiconv/.conan/$EPM_PROFILE/$EPM_SCHEME
    - libiconv/.epm
  script:
  - cd libiconv
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME
  parallel:
    matrix:
    - EPM_PROFILE: ['vs2019', 'vs2019d']
      EPM_SCHEME: ['static', 'shared']

    # =========================================
    # gcc5-armv8 armv8 build
    # =========================================
libiconv:gcc5-armv8@build:
  stage: build
  tags:
  - Linux
  - builder
  - docker
  - workbench:oss-0.2
  image: 172.16.0.119:8482/edgetoolkit/gcc5-armv8
  artifacts:
    paths:
    - libiconv/.conan/$EPM_PROFILE/$EPM_SCHEME
    - libiconv/.epm
  script:
  - cd libiconv
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc5-armv8d', 'gcc5-armv8']
      EPM_SCHEME: ['static', 'shared']

    # =========================================
    # gcc5 x86_64 build
    # =========================================
libiconv:gcc5@build:
  stage: build
  tags:
  - Linux
  - builder
  - docker
  - workbench:oss-0.2
  image: 172.16.0.119:8482/edgetoolkit/gcc5
  artifacts:
    paths:
    - libiconv/.conan/$EPM_PROFILE/$EPM_SCHEME
    - libiconv/.epm
  script:
  - cd libiconv
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc5', 'gcc5d']
      EPM_SCHEME: ['static', 'shared']

    # =========================================
    # gcc5-armv7 armv7 build
    # =========================================
libiconv:gcc5-armv7@build:
  stage: build
  tags:
  - Linux
  - builder
  - docker
  - workbench:oss-0.2
  image: 172.16.0.119:8482/edgetoolkit/gcc5-armv7
  artifacts:
    paths:
    - libiconv/.conan/$EPM_PROFILE/$EPM_SCHEME
    - libiconv/.epm
  script:
  - cd libiconv
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc5-armv7', 'gcc5-armv7d']
      EPM_SCHEME: ['static', 'shared']

    # =================================
    # MSVC test
    # =================================
libiconv:MSVC@test:
  stage: test
  tags:
  - Windows
  - runner
  - workbench:oss-0.2
  dependencies:
  - libiconv:MSVC@build
  script: |
    cd libiconv
    $EPM_SANDBOX_STORAGE = ".conan/$EPM_PROFILE/$EPM_SCHEME" 
        
    .epm/$EPM_PROFILE@$EPM_SCHEME/sandbox/test_package
    
  parallel:
    matrix:
    - EPM_PROFILE: ['vs2019', 'vs2019d']
      EPM_SCHEME: ['static', 'shared']




    # =========================================
    # gcc5 x86_64 test
    # =========================================
libiconv:gcc5@test:
  stage: test
  tags:
  - Linux
  - runner
  - docker
  - workbench:oss-0.2
  image: edgetoolkit/ubuntu:xenial
  dependencies:
  - libiconv:gcc5@build
  script:
    cd libiconv
    export EPM_SANDBOX_STORAGE = ".conan/$EPM_PROFILE/$EPM_SCHEME"    
        
    .epm/$EPM_PROFILE@$EPM_SCHEME/sandbox/test_package
    
    
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc5', 'gcc5d']
      EPM_SCHEME: ['static', 'shared']



    # =================================
    # Deploy to conan repo
    # =================================
libiconv@deploy:
  stage: deploy
  tags:
  - conan
  - deployer
  - workbench:oss-0.2
  dependencies:
  - libiconv:gcc5-armv8@build
  - libiconv:gcc5@build
  - libiconv:gcc5-armv7@build
  - libiconv:MSVC@build
  script: |
    set -e
    cd libiconv
    PROFILES=(
      gcc5-armv8d gcc5-armv8
      gcc5 gcc5d
      gcc5-armv7 gcc5-armv7d
      vs2019 vs2019d
    )

    for profile in ${PROFILES[*]}
    do
      for scheme in static shared
      do
        export EPM_PROFILE=$profile
        export EPM_FPROFILE=$scheme
        echo [libiconv] - Upload...  $profile $shcme
        epm upload --storage .conan/$profile/$scheme
      done
    done 