
stages:
- build
- deploy


    # =================================
    # MSVC build
    # =================================
nasm:MSVC@build:
  stage: build
  tags:
  - Windows
  - builder
  - workbench:Z1
  artifacts:
    paths:
    - nasm/.conan/$EPM_PROFILE/$EPM_SCHEME
    - nasm/.epm
  script:
  - cd nasm
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME   --clear
  parallel:
    matrix:
    - EPM_PROFILE: ['vs2019']
      EPM_SCHEME: ['none']

    # =========================================
    # gcc5 x86_64 build
    # =========================================
nasm:gcc5@build:
  stage: build
  tags:
  - Linux
  - builder
  - docker
  - workbench:Z1
  image: edgetoolkit/gcc5
  artifacts:
    paths:
    - nasm/.conan/$EPM_PROFILE/$EPM_SCHEME
    - nasm/.epm
  script:
  - cd nasm
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME  --clear
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc5']
      EPM_SCHEME: ['none']

    # =================================
    # Deploy to conan repo
    # =================================
nasm@deploy:
  stage: deploy
  tags:
  - conan
  - deployer
  - workbench:Z1

  dependencies:
  - nasm:MSVC@build
  - nasm:gcc5@build
  script:
  - cd nasm
  - epm -p vs2019 -s none upload --storage .conan/vs2019/none
  - epm -p gcc5 -s none upload --storage .conan/gcc5/none