stages:
- build
- test
- deploy

    # =================================
    # MSVC build
    # =================================
openssl:MSVC@build:
  stage: build
  tags:
  - Windows
  - builder
  - workbench:oss-0.2
  artifacts:
    paths:
    - openssl/.conan/$EPM_PROFILE/$EPM_SCHEME
    - openssl/.epm
  script:
  - cd openssl
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME
  parallel:
    matrix:
    - EPM_PROFILE: ['vs2019d', 'vs2019']
      EPM_SCHEME: ['shared', 'static']

    # =========================================
    # gcc6 x86_64 build
    # =========================================
openssl:gcc6@build:
  stage: build
  tags:
  - Linux
  - builder
  - docker
  - workbench:oss-0.2
  image: 172.16.0.119:8482/edgetoolkit/gcc6
  artifacts:
    paths:
    - openssl/.conan/$EPM_PROFILE/$EPM_SCHEME
    - openssl/.epm
  script:
  - cd openssl
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc6d', 'gcc6']
      EPM_SCHEME: ['shared', 'static']

    # =========================================
    # gcc7-armv7 armv7 build
    # =========================================
openssl:gcc7-armv7@build:
  stage: build
  tags:
  - Linux
  - builder
  - docker
  - workbench:oss-0.2
  image: 172.16.0.119:8482/edgetoolkit/gcc7-armv7
  artifacts:
    paths:
    - openssl/.conan/$EPM_PROFILE/$EPM_SCHEME
    - openssl/.epm
  script:
  - cd openssl
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc7-armv7']
      EPM_SCHEME: ['shared', 'static']

    # =========================================
    # gcc5-armv7 armv7 build
    # =========================================
openssl:gcc5-armv7@build:
  stage: build
  tags:
  - Linux
  - builder
  - docker
  - workbench:oss-0.2
  image: 172.16.0.119:8482/edgetoolkit/gcc5-armv7
  artifacts:
    paths:
    - openssl/.conan/$EPM_PROFILE/$EPM_SCHEME
    - openssl/.epm
  script:
  - cd openssl
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc5-armv7']
      EPM_SCHEME: ['shared', 'static']

    # =========================================
    # gcc7-armv8 armv8 build
    # =========================================
openssl:gcc7-armv8@build:
  stage: build
  tags:
  - Linux
  - builder
  - docker
  - workbench:oss-0.2
  image: 172.16.0.119:8482/edgetoolkit/gcc7-armv8
  artifacts:
    paths:
    - openssl/.conan/$EPM_PROFILE/$EPM_SCHEME
    - openssl/.epm
  script:
  - cd openssl
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc7-armv8']
      EPM_SCHEME: ['shared', 'static']

    # =========================================
    # gcc5 x86_64 build
    # =========================================
openssl:gcc5@build:
  stage: build
  tags:
  - Linux
  - builder
  - docker
  - workbench:oss-0.2
  image: 172.16.0.119:8482/edgetoolkit/gcc5
  artifacts:
    paths:
    - openssl/.conan/$EPM_PROFILE/$EPM_SCHEME
    - openssl/.epm
  script:
  - cd openssl
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc5', 'gcc5d']
      EPM_SCHEME: ['shared', 'static']

    # =========================================
    # gcc7 x86_64 build
    # =========================================
openssl:gcc7@build:
  stage: build
  tags:
  - Linux
  - builder
  - docker
  - workbench:oss-0.2
  image: 172.16.0.119:8482/edgetoolkit/gcc7
  artifacts:
    paths:
    - openssl/.conan/$EPM_PROFILE/$EPM_SCHEME
    - openssl/.epm
  script:
  - cd openssl
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc7d', 'gcc7']
      EPM_SCHEME: ['shared', 'static']

    # =========================================
    # gcc5-armv8 armv8 build
    # =========================================
openssl:gcc5-armv8@build:
  stage: build
  tags:
  - Linux
  - builder
  - docker
  - workbench:oss-0.2
  image: 172.16.0.119:8482/edgetoolkit/gcc5-armv8
  artifacts:
    paths:
    - openssl/.conan/$EPM_PROFILE/$EPM_SCHEME
    - openssl/.epm
  script:
  - cd openssl
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc5-armv8']
      EPM_SCHEME: ['shared', 'static']

    # =========================================
    # gcc6-armv8 armv8 build
    # =========================================
openssl:gcc6-armv8@build:
  stage: build
  tags:
  - Linux
  - builder
  - docker
  - workbench:oss-0.2
  image: 172.16.0.119:8482/edgetoolkit/gcc6-armv8
  artifacts:
    paths:
    - openssl/.conan/$EPM_PROFILE/$EPM_SCHEME
    - openssl/.epm
  script:
  - cd openssl
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc6-armv8']
      EPM_SCHEME: ['shared', 'static']

    # =========================================
    # gcc6-armv7 armv7 build
    # =========================================
openssl:gcc6-armv7@build:
  stage: build
  tags:
  - Linux
  - builder
  - docker
  - workbench:oss-0.2
  image: 172.16.0.119:8482/edgetoolkit/gcc6-armv7
  artifacts:
    paths:
    - openssl/.conan/$EPM_PROFILE/$EPM_SCHEME
    - openssl/.epm
  script:
  - cd openssl
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc6-armv7']
      EPM_SCHEME: ['shared', 'static']

    # =================================
    # MSVC test
    # =================================
openssl:MSVC@test:
  stage: test
  tags:
  - Windows
  - runner
  - workbench:oss-0.2
  dependencies:
  - openssl:MSVC@build
  script: |
    cd openssl
    $EPM_SANDBOX_STORAGE = ".conan/$EPM_PROFILE/$EPM_SCHEME" 
        
    .epm/$EPM_PROFILE@$EPM_SCHEME/sandbox/test_package
    
  parallel:
    matrix:
    - EPM_PROFILE: ['vs2019d', 'vs2019']
      EPM_SCHEME: ['shared', 'static']


    # =========================================
    # gcc6 x86_64 test
    # =========================================
openssl:gcc6@test:
  stage: test
  tags:
  - Linux
  - runner
  - docker
  - workbench:oss-0.2
  image: edgetoolkit/ubuntu:xenial
  dependencies:
  - openssl:gcc6@build
  script:
    cd openssl
    export EPM_SANDBOX_STORAGE = ".conan/$EPM_PROFILE/$EPM_SCHEME"    
        
    .epm/$EPM_PROFILE@$EPM_SCHEME/sandbox/test_package
    
    
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc6d', 'gcc6']
      EPM_SCHEME: ['shared', 'static']








    # =========================================
    # gcc5 x86_64 test
    # =========================================
openssl:gcc5@test:
  stage: test
  tags:
  - Linux
  - runner
  - docker
  - workbench:oss-0.2
  image: edgetoolkit/ubuntu:xenial
  dependencies:
  - openssl:gcc5@build
  script:
    cd openssl
    export EPM_SANDBOX_STORAGE = ".conan/$EPM_PROFILE/$EPM_SCHEME"    
        
    .epm/$EPM_PROFILE@$EPM_SCHEME/sandbox/test_package
    
    
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc5', 'gcc5d']
      EPM_SCHEME: ['shared', 'static']


    # =========================================
    # gcc7 x86_64 test
    # =========================================
openssl:gcc7@test:
  stage: test
  tags:
  - Linux
  - runner
  - docker
  - workbench:oss-0.2
  image: edgetoolkit/ubuntu:xenial
  dependencies:
  - openssl:gcc7@build
  script:
    cd openssl
    export EPM_SANDBOX_STORAGE = ".conan/$EPM_PROFILE/$EPM_SCHEME"    
        
    .epm/$EPM_PROFILE@$EPM_SCHEME/sandbox/test_package
    
    
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc7d', 'gcc7']
      EPM_SCHEME: ['shared', 'static']







    # =================================
    # Deploy to conan repo
    # =================================
openssl@deploy:
  stage: deploy
  tags:
  - conan
  - deployer
  - workbench:oss-0.2
  dependencies:
  - openssl:MSVC@build
  - openssl:gcc6@build
  - openssl:gcc7-armv7@build
  - openssl:gcc5-armv7@build
  - openssl:gcc7-armv8@build
  - openssl:gcc5@build
  - openssl:gcc7@build
  - openssl:gcc5-armv8@build
  - openssl:gcc6-armv8@build
  - openssl:gcc6-armv7@build
  script: |
    set -e
    cd openssl
    PROFILES=(
      vs2019d vs2019
      gcc6d gcc6
      gcc7-armv7
      gcc5-armv7
      gcc7-armv8
      gcc5 gcc5d
      gcc7d gcc7
      gcc5-armv8
      gcc6-armv8
      gcc6-armv7
    )

    for profile in ${PROFILES[*]}
    do
      for scheme in shared static
      do
        export EPM_PROFILE=$profile
        export EPM_FPROFILE=$scheme
        echo [openssl] - Upload...  $profile $shcme
        epm upload --storage .conan/$profile/$scheme
      done
    done 