stages:
- build
- test
- deploy

    # =================================
    # MSVC build
    # =================================
protobuf-c:MSVC@build:
  stage: build
  tags:
  - Windows
  - builder
  - workbench:oss-0.2
  artifacts:
    paths:
    - protobuf-c/.conan/$EPM_PROFILE/$EPM_SCHEME
    - protobuf-c/.epm
  script:
  - cd protobuf-c
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME
  parallel:
    matrix:
    - EPM_PROFILE: ['vs2019d', 'vs2019']
      EPM_SCHEME: ['shared', 'static']

    # =========================================
    # gcc6-armv8 armv8 build
    # =========================================
protobuf-c:gcc6-armv8@build:
  stage: build
  tags:
  - Linux
  - builder
  - docker
  - workbench:oss-0.2
  image: 172.16.0.119:8482/edgetoolkit/gcc6-armv8
  artifacts:
    paths:
    - protobuf-c/.conan/$EPM_PROFILE/$EPM_SCHEME
    - protobuf-c/.epm
  script:
  - cd protobuf-c
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc6-armv8', 'gcc6-armv8d']
      EPM_SCHEME: ['shared', 'static']

    # =========================================
    # gcc6 x86_64 build
    # =========================================
protobuf-c:gcc6@build:
  stage: build
  tags:
  - Linux
  - builder
  - docker
  - workbench:oss-0.2
  image: 172.16.0.119:8482/edgetoolkit/gcc6
  artifacts:
    paths:
    - protobuf-c/.conan/$EPM_PROFILE/$EPM_SCHEME
    - protobuf-c/.epm
  script:
  - cd protobuf-c
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc6', 'gcc6d']
      EPM_SCHEME: ['shared', 'static']

    # =========================================
    # gcc7-armv7 armv7 build
    # =========================================
protobuf-c:gcc7-armv7@build:
  stage: build
  tags:
  - Linux
  - builder
  - docker
  - workbench:oss-0.2
  image: 172.16.0.119:8482/edgetoolkit/gcc7-armv7
  artifacts:
    paths:
    - protobuf-c/.conan/$EPM_PROFILE/$EPM_SCHEME
    - protobuf-c/.epm
  script:
  - cd protobuf-c
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc7-armv7', 'gcc7-armv7d']
      EPM_SCHEME: ['shared', 'static']

    # =========================================
    # gcc5 x86_64 build
    # =========================================
protobuf-c:gcc5@build:
  stage: build
  tags:
  - Linux
  - builder
  - docker
  - workbench:oss-0.2
  image: 172.16.0.119:8482/edgetoolkit/gcc5
  artifacts:
    paths:
    - protobuf-c/.conan/$EPM_PROFILE/$EPM_SCHEME
    - protobuf-c/.epm
  script:
  - cd protobuf-c
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc5', 'gcc5d']
      EPM_SCHEME: ['shared', 'static']

    # =========================================
    # gcc7 x86_64 build
    # =========================================
protobuf-c:gcc7@build:
  stage: build
  tags:
  - Linux
  - builder
  - docker
  - workbench:oss-0.2
  image: 172.16.0.119:8482/edgetoolkit/gcc7
  artifacts:
    paths:
    - protobuf-c/.conan/$EPM_PROFILE/$EPM_SCHEME
    - protobuf-c/.epm
  script:
  - cd protobuf-c
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc7d', 'gcc7']
      EPM_SCHEME: ['shared', 'static']

    # =========================================
    # gcc5-armv8 armv8 build
    # =========================================
protobuf-c:gcc5-armv8@build:
  stage: build
  tags:
  - Linux
  - builder
  - docker
  - workbench:oss-0.2
  image: 172.16.0.119:8482/edgetoolkit/gcc5-armv8
  artifacts:
    paths:
    - protobuf-c/.conan/$EPM_PROFILE/$EPM_SCHEME
    - protobuf-c/.epm
  script:
  - cd protobuf-c
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc5-armv8d', 'gcc5-armv8']
      EPM_SCHEME: ['shared', 'static']

    # =========================================
    # gcc5-armv7 armv7 build
    # =========================================
protobuf-c:gcc5-armv7@build:
  stage: build
  tags:
  - Linux
  - builder
  - docker
  - workbench:oss-0.2
  image: 172.16.0.119:8482/edgetoolkit/gcc5-armv7
  artifacts:
    paths:
    - protobuf-c/.conan/$EPM_PROFILE/$EPM_SCHEME
    - protobuf-c/.epm
  script:
  - cd protobuf-c
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc5-armv7']
      EPM_SCHEME: ['shared', 'static']

    # =========================================
    # gcc6-armv7 armv7 build
    # =========================================
protobuf-c:gcc6-armv7@build:
  stage: build
  tags:
  - Linux
  - builder
  - docker
  - workbench:oss-0.2
  image: 172.16.0.119:8482/edgetoolkit/gcc6-armv7
  artifacts:
    paths:
    - protobuf-c/.conan/$EPM_PROFILE/$EPM_SCHEME
    - protobuf-c/.epm
  script:
  - cd protobuf-c
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc6-armv7', 'gcc6-armv7d']
      EPM_SCHEME: ['shared', 'static']

    # =========================================
    # gcc7-armv8 armv8 build
    # =========================================
protobuf-c:gcc7-armv8@build:
  stage: build
  tags:
  - Linux
  - builder
  - docker
  - workbench:oss-0.2
  image: 172.16.0.119:8482/edgetoolkit/gcc7-armv8
  artifacts:
    paths:
    - protobuf-c/.conan/$EPM_PROFILE/$EPM_SCHEME
    - protobuf-c/.epm
  script:
  - cd protobuf-c
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc7-armv8d', 'gcc7-armv8']
      EPM_SCHEME: ['shared', 'static']

    # =================================
    # MSVC test
    # =================================
protobuf-c:MSVC@test:
  stage: test
  tags:
  - Windows
  - runner
  - workbench:oss-0.2
  dependencies:
  - protobuf-c:MSVC@build
  script: |
    cd protobuf-c
    $EPM_SANDBOX_STORAGE = ".conan/$EPM_PROFILE/$EPM_SCHEME" 
        
    .epm/$EPM_PROFILE@$EPM_SCHEME/sandbox/test_package
    
  parallel:
    matrix:
    - EPM_PROFILE: ['vs2019d', 'vs2019']
      EPM_SCHEME: ['shared', 'static']




    # =========================================
    # gcc6 x86_64 test
    # =========================================
protobuf-c:gcc6@test:
  stage: test
  tags:
  - Linux
  - runner
  - docker
  - workbench:oss-0.2
  image: edgetoolkit/ubuntu:xenial
  dependencies:
  - protobuf-c:gcc6@build
  script:
    cd protobuf-c
    export EPM_SANDBOX_STORAGE = ".conan/$EPM_PROFILE/$EPM_SCHEME"    
        
    .epm/$EPM_PROFILE@$EPM_SCHEME/sandbox/test_package
    
    
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc6', 'gcc6d']
      EPM_SCHEME: ['shared', 'static']




    # =========================================
    # gcc5 x86_64 test
    # =========================================
protobuf-c:gcc5@test:
  stage: test
  tags:
  - Linux
  - runner
  - docker
  - workbench:oss-0.2
  image: edgetoolkit/ubuntu:xenial
  dependencies:
  - protobuf-c:gcc5@build
  script:
    cd protobuf-c
    export EPM_SANDBOX_STORAGE = ".conan/$EPM_PROFILE/$EPM_SCHEME"    
        
    .epm/$EPM_PROFILE@$EPM_SCHEME/sandbox/test_package
    
    
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc5', 'gcc5d']
      EPM_SCHEME: ['shared', 'static']


    # =========================================
    # gcc7 x86_64 test
    # =========================================
protobuf-c:gcc7@test:
  stage: test
  tags:
  - Linux
  - runner
  - docker
  - workbench:oss-0.2
  image: edgetoolkit/ubuntu:xenial
  dependencies:
  - protobuf-c:gcc7@build
  script:
    cd protobuf-c
    export EPM_SANDBOX_STORAGE = ".conan/$EPM_PROFILE/$EPM_SCHEME"    
        
    .epm/$EPM_PROFILE@$EPM_SCHEME/sandbox/test_package
    
    
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc7d', 'gcc7']
      EPM_SCHEME: ['shared', 'static']









    # =================================
    # Deploy to conan repo
    # =================================
protobuf-c@deploy:
  stage: deploy
  tags:
  - conan
  - deployer
  - workbench:oss-0.2
  dependencies:
  - protobuf-c:gcc6-armv8@build
  - protobuf-c:gcc6@build
  - protobuf-c:MSVC@build
  - protobuf-c:gcc7-armv7@build
  - protobuf-c:gcc5@build
  - protobuf-c:gcc7@build
  - protobuf-c:gcc5-armv8@build
  - protobuf-c:gcc5-armv7@build
  - protobuf-c:gcc6-armv7@build
  - protobuf-c:gcc7-armv8@build
  script: |
    set -e
    cd protobuf-c
    PROFILES=(
      gcc6-armv8 gcc6-armv8d
      gcc6 gcc6d
      vs2019d vs2019
      gcc7-armv7 gcc7-armv7d
      gcc5 gcc5d
      gcc7d gcc7
      gcc5-armv8d gcc5-armv8
      gcc5-armv7
      gcc6-armv7 gcc6-armv7d
      gcc7-armv8d gcc7-armv8
    )

    for profile in ${PROFILES[*]}
    do
      for scheme in shared static
      do
        export EPM_PROFILE=$profile
        export EPM_FPROFILE=$scheme
        echo [protobuf-c] - Upload...  $profile $shcme
        epm upload --storage .conan/$profile/$scheme
      done
    done 