stages:
- build
- test
- deploy

    # =================================
    # MSVC build
    # =================================
pthreads4w:MSVC@build:
  stage: build
  tags:
  - Windows
  - builder
  - workbench:Z1
  artifacts:
    paths:
    - pthreads4w/.conan/$EPM_PROFILE/$EPM_SCHEME
    - pthreads4w/.epm
  script:
  - cd pthreads4w
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME  --with-deps --clear
  parallel:
    matrix:
    - EPM_PROFILE: ['vs2019', 'vs2019d']
      EPM_SCHEME: ['static', 'shared']

    # =================================
    # MSVC test
    # =================================
pthreads4w:MSVC@test:
  stage: test
  tags:
  - Windows
  - runner
  - workbench:Z1
  dependencies:
  - pthreads4w:MSVC@build
  script:
  - cd pthreads4w
  - $env:EPM_SANDBOX_STORAGE=".conan/$EPM_PROFILE/$EPM_SCHEME" 
        
  - . .epm/$EPM_PROFILE@$EPM_SCHEME/sandbox/test_package
    
  parallel:
    matrix:
    - EPM_PROFILE: ['vs2019', 'vs2019d']
      EPM_SCHEME: ['static', 'shared']

    # =================================
    # Deploy to conan repo
    # =================================
pthreads4w@deploy:
  stage: deploy
  tags:
  - conan
  - deployer
  - workbench:Z1

  image: 172.16.0.119:8482/edgetoolkit/gcc5

  dependencies:
  - pthreads4w:MSVC@build
  script:
  - cd pthreads4w
  - epm -p vs2019 -s static upload --storage .conan/vs2019/static
  - epm -p vs2019 -s shared upload --storage .conan/vs2019/shared
  - epm -p vs2019d -s static upload --storage .conan/vs2019d/static
  - epm -p vs2019d -s shared upload --storage .conan/vs2019d/shared