stages:
- build
- test
- deploy

    # =================================
    # MSVC build
    # =================================
pthreads4w:MSVC@build:
  stage: build
  tags:
  - Windows
  - builder
  - workbench:Z1
  artifacts:
    paths:
    - pthreads4w/.conan/$EPM_PROFILE/$EPM_SCHEME
    - pthreads4w/.epm
  script:
  - cd pthreads4w
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME
  parallel:
    matrix:
    - EPM_PROFILE: ['vs2019d', 'vs2019']
      EPM_SCHEME: ['shared', 'static']

    # =================================
    # MSVC test
    # =================================
pthreads4w:MSVC@test:
  stage: test
  tags:
  - Windows
  - runner
  - workbench:Z1
  dependencies:
  - pthreads4w:MSVC@build
  script: |
    cd pthreads4w
    $EPM_SANDBOX_STORAGE = ".conan/$EPM_PROFILE/$EPM_SCHEME" 
        
    .epm/$EPM_PROFILE@$EPM_SCHEME/sandbox/test_package
    
  parallel:
    matrix:
    - EPM_PROFILE: ['vs2019d', 'vs2019']
      EPM_SCHEME: ['shared', 'static']

    # =================================
    # Deploy to conan repo
    # =================================
pthreads4w@deploy:
  stage: deploy
  tags:
  - conan
  - deployer
  - workbench:oss-0.2
  dependencies:
  - pthreads4w:MSVC@build
  script: |
    set -e
    cd pthreads4w
    PROFILES=(
      vs2019d vs2019
    )

    for profile in ${PROFILES[*]}
    do
      for scheme in shared static
      do
        export EPM_PROFILE=$profile
        export EPM_FPROFILE=$scheme
        echo [pthreads4w] - Upload...  $profile $shcme
        epm upload --storage .conan/$profile/$scheme
      done
    done 