stages:
- build
- test
- deploy

    # =================================
    # MSVC build
    # =================================
sqlite3:MSVC@build:
  stage: build
  tags:
  - Windows
  - builder
  - workbench:Z1
  artifacts:
    paths:
    - sqlite3/.conan/$EPM_PROFILE/$EPM_SCHEME
    - sqlite3/.epm
  script:
  - cd sqlite3
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME  --with-deps --clear
  parallel:
    matrix:
    - EPM_PROFILE: ['vs2019', 'vs2019d']
      EPM_SCHEME: ['shared', 'static']

    # =========================================
    # gcc5 x86_64 build
    # =========================================
sqlite3:gcc5@build:
  stage: build
  tags:
  - Linux
  - builder
  - docker
  - workbench:Z1
  image: 172.16.0.119:8482/edgetoolkit/gcc5
  artifacts:
    paths:
    - sqlite3/.conan/$EPM_PROFILE/$EPM_SCHEME
    - sqlite3/.epm
  script:
  - cd sqlite3
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME --with-deps --clear
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc5d', 'gcc5']
      EPM_SCHEME: ['shared', 'static']

    # =========================================
    # gcc5-armv7 armv7 build
    # =========================================
sqlite3:gcc5-armv7@build:
  stage: build
  tags:
  - Linux
  - builder
  - docker
  - workbench:Z1
  image: 172.16.0.119:8482/edgetoolkit/gcc5-armv7
  artifacts:
    paths:
    - sqlite3/.conan/$EPM_PROFILE/$EPM_SCHEME
    - sqlite3/.epm
  script:
  - cd sqlite3
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME --with-deps --clear
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc5-armv7d', 'gcc5-armv7']
      EPM_SCHEME: ['shared', 'static']

    # =========================================
    # gcc5-armv8 armv8 build
    # =========================================
sqlite3:gcc5-armv8@build:
  stage: build
  tags:
  - Linux
  - builder
  - docker
  - workbench:Z1
  image: 172.16.0.119:8482/edgetoolkit/gcc5-armv8
  artifacts:
    paths:
    - sqlite3/.conan/$EPM_PROFILE/$EPM_SCHEME
    - sqlite3/.epm
  script:
  - cd sqlite3
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME --with-deps --clear
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc5-armv8', 'gcc5-armv8d']
      EPM_SCHEME: ['shared', 'static']

    # =================================
    # MSVC test
    # =================================
sqlite3:MSVC@test:
  stage: test
  tags:
  - Windows
  - runner
  - workbench:Z1
  dependencies:
  - sqlite3:MSVC@build
  script:
  - cd sqlite3
  - $EPM_SANDBOX_STORAGE=".conan/$EPM_PROFILE/$EPM_SCHEME" 
        
  - .epm/$EPM_PROFILE@$EPM_SCHEME/sandbox/test_package
    
  parallel:
    matrix:
    - EPM_PROFILE: ['vs2019', 'vs2019d']
      EPM_SCHEME: ['shared', 'static']


    # =========================================
    # gcc5 x86_64 test
    # =========================================
sqlite3:gcc5@test:
  stage: test
  tags:
  - Linux
  - runner
  - docker
  - workbench:Z1
  image: edgetoolkit/ubuntu:xenial
  dependencies:
  - sqlite3:gcc5@build
  script:
  - cd sqlite3
  - export EPM_SANDBOX_STORAGE=".conan/$EPM_PROFILE/$EPM_SCHEME"    
        
  - .epm/$EPM_PROFILE@$EPM_SCHEME/sandbox/test_package
    
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc5d', 'gcc5']
      EPM_SCHEME: ['shared', 'static']





    # =================================
    # Deploy to conan repo
    # =================================
sqlite3@deploy:
  stage: deploy
  tags:
  - conan
  - deployer
  - workbench:Z1

  image: 172.16.0.119:8482/edgetoolkit/gcc5

  dependencies:
  - sqlite3:gcc5@build
  - sqlite3:MSVC@build
  - sqlite3:gcc5-armv7@build
  - sqlite3:gcc5-armv8@build
  script:
  - epm -p gcc5d -s shared upload --storage .conan/gcc5d/shared
  - epm -p gcc5d -s static upload --storage .conan/gcc5d/static
  - epm -p gcc5 -s shared upload --storage .conan/gcc5/shared
  - epm -p gcc5 -s static upload --storage .conan/gcc5/static
  - epm -p vs2019 -s shared upload --storage .conan/vs2019/shared
  - epm -p vs2019 -s static upload --storage .conan/vs2019/static
  - epm -p vs2019d -s shared upload --storage .conan/vs2019d/shared
  - epm -p vs2019d -s static upload --storage .conan/vs2019d/static
  - epm -p gcc5-armv7d -s shared upload --storage .conan/gcc5-armv7d/shared
  - epm -p gcc5-armv7d -s static upload --storage .conan/gcc5-armv7d/static
  - epm -p gcc5-armv7 -s shared upload --storage .conan/gcc5-armv7/shared
  - epm -p gcc5-armv7 -s static upload --storage .conan/gcc5-armv7/static
  - epm -p gcc5-armv8 -s shared upload --storage .conan/gcc5-armv8/shared
  - epm -p gcc5-armv8 -s static upload --storage .conan/gcc5-armv8/static
  - epm -p gcc5-armv8d -s shared upload --storage .conan/gcc5-armv8d/shared
  - epm -p gcc5-armv8d -s static upload --storage .conan/gcc5-armv8d/static