
stages:
- build
- deploy


    # =================================
    # MSVC build
    # =================================
winflexbison:MSVC@build:
  stage: build
  tags:
  - Windows
  - builder
  - workbench:Z1
  artifacts:
    paths:
    - winflexbison/.conan/$EPM_PROFILE/$EPM_SCHEME
    - winflexbison/.epm
  script:
  - cd winflexbison
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME   --clear
  parallel:
    matrix:
    - EPM_PROFILE: ['vs2019']
      EPM_SCHEME: ['none']

    # =================================
    # Deploy to conan repo
    # =================================
winflexbison@deploy:
  stage: deploy
  tags:
  - conan
  - deployer
  - workbench:Z1

  dependencies:
  - winflexbison:MSVC@build
  script:
  - cd winflexbison
  - epm -p vs2019 -s none upload --storage .conan/vs2019/none