stages:
- build
- test
- deploy

    # =================================
    # MSVC build
    # =================================
zlib:MSVC@build:
  stage: build
  tags:
  - Windows
  - builder
  - workbench:oss-0.2
  artifacts:
    paths:
    - zlib/.conan/$EPM_PROFILE/$EPM_SCHEME
    - zlib/.epm
  script:
  - cd zlib
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME
  parallel:
    matrix:
    - EPM_PROFILE: ['vs2019', 'vs2019d']
      EPM_SCHEME: ['static', 'shared']

    # =========================================
    # gcc7-armv7 armv7 build
    # =========================================
zlib:@build:
  stage: build
  tags:
  - Linux
  - builder
  - docker
  - workbench:oss-0.2
  image: edgetoolkit/
  artifacts:
    paths:
    - zlib/.conan/$EPM_PROFILE/$EPM_SCHEME
    - zlib/.epm
  script:
  - cd zlib
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc7-armv7', 'gcc7-armv7d']
      EPM_SCHEME: ['static', 'shared']

    # =========================================
    # gcc6-armv8 armv8 build
    # =========================================
zlib:@build:
  stage: build
  tags:
  - Linux
  - builder
  - docker
  - workbench:oss-0.2
  image: edgetoolkit/
  artifacts:
    paths:
    - zlib/.conan/$EPM_PROFILE/$EPM_SCHEME
    - zlib/.epm
  script:
  - cd zlib
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc6-armv8d', 'gcc6-armv8']
      EPM_SCHEME: ['static', 'shared']

    # =========================================
    # gcc7-armv8 armv8 build
    # =========================================
zlib:@build:
  stage: build
  tags:
  - Linux
  - builder
  - docker
  - workbench:oss-0.2
  image: edgetoolkit/
  artifacts:
    paths:
    - zlib/.conan/$EPM_PROFILE/$EPM_SCHEME
    - zlib/.epm
  script:
  - cd zlib
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc7-armv8d', 'gcc7-armv8']
      EPM_SCHEME: ['static', 'shared']

    # =========================================
    # gcc5-armv7 armv7 build
    # =========================================
zlib:@build:
  stage: build
  tags:
  - Linux
  - builder
  - docker
  - workbench:oss-0.2
  image: edgetoolkit/
  artifacts:
    paths:
    - zlib/.conan/$EPM_PROFILE/$EPM_SCHEME
    - zlib/.epm
  script:
  - cd zlib
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc5-armv7d', 'gcc5-armv7']
      EPM_SCHEME: ['static', 'shared']

    # =========================================
    # gcc5 x86_64 build
    # =========================================
zlib:@build:
  stage: build
  tags:
  - Linux
  - builder
  - docker
  - workbench:oss-0.2
  image: edgetoolkit/
  artifacts:
    paths:
    - zlib/.conan/$EPM_PROFILE/$EPM_SCHEME
    - zlib/.epm
  script:
  - cd zlib
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc5d', 'gcc5']
      EPM_SCHEME: ['static', 'shared']

    # =========================================
    # gcc5-armv8 armv8 build
    # =========================================
zlib:@build:
  stage: build
  tags:
  - Linux
  - builder
  - docker
  - workbench:oss-0.2
  image: edgetoolkit/
  artifacts:
    paths:
    - zlib/.conan/$EPM_PROFILE/$EPM_SCHEME
    - zlib/.epm
  script:
  - cd zlib
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc5-armv8', 'gcc5-armv8d']
      EPM_SCHEME: ['static', 'shared']

    # =========================================
    # gcc6-armv7 armv7 build
    # =========================================
zlib:@build:
  stage: build
  tags:
  - Linux
  - builder
  - docker
  - workbench:oss-0.2
  image: edgetoolkit/
  artifacts:
    paths:
    - zlib/.conan/$EPM_PROFILE/$EPM_SCHEME
    - zlib/.epm
  script:
  - cd zlib
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc6-armv7', 'gcc6-armv7d']
      EPM_SCHEME: ['static', 'shared']

    # =========================================
    # gcc6 x86_64 build
    # =========================================
zlib:@build:
  stage: build
  tags:
  - Linux
  - builder
  - docker
  - workbench:oss-0.2
  image: edgetoolkit/
  artifacts:
    paths:
    - zlib/.conan/$EPM_PROFILE/$EPM_SCHEME
    - zlib/.epm
  script:
  - cd zlib
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc6d', 'gcc6']
      EPM_SCHEME: ['static', 'shared']

    # =========================================
    # gcc7 x86_64 build
    # =========================================
zlib:@build:
  stage: build
  tags:
  - Linux
  - builder
  - docker
  - workbench:oss-0.2
  image: edgetoolkit/
  artifacts:
    paths:
    - zlib/.conan/$EPM_PROFILE/$EPM_SCHEME
    - zlib/.epm
  script:
  - cd zlib
  - epm create --archive .conan/$EPM_PROFILE/$EPM_SCHEME
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc7', 'gcc7d']
      EPM_SCHEME: ['static', 'shared']

    # =================================
    # MSVC test
    # =================================
zlib:MSVC@test:
  stage: build
  tags:
  - Windows
  - runner
  - workbench:oss-0.2
  dependencies:
  - zlib:MSVC@build
  script: |
    cd zlib
    $EPM_SANDBOX_STORAGE = ".conan/$EPM_PROFILE/$EPM_SCHEME"    
    .epm/$EPM_PROFILE@$EPM_SCHEME/sandbox/['test_package']
  parallel:
    matrix:
    - EPM_PROFILE: ['vs2019', 'vs2019d']
      EPM_SCHEME: ['static', 'shared']










    # =========================================
    # gcc5 x86_64 test
    # =========================================
zlib:@build:
  stage: build
  tags:
  - Linux
  - runner
  - docker
  - workbench:oss-0.2
  image: edgetoolkit/ubuntu:xenial
  dependencies:
  - zlib:gcc5@build
  script:
    cd zlib
    export EPM_SANDBOX_STORAGE = ".conan/$EPM_PROFILE/$EPM_SCHEME"    
    .epm/$EPM_PROFILE@$EPM_SCHEME/sandbox/['test_package']
    
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc5d', 'gcc5']
      EPM_SCHEME: ['static', 'shared']






    # =========================================
    # gcc6 x86_64 test
    # =========================================
zlib:@build:
  stage: build
  tags:
  - Linux
  - runner
  - docker
  - workbench:oss-0.2
  image: edgetoolkit/ubuntu:xenial
  dependencies:
  - zlib:gcc6@build
  script:
    cd zlib
    export EPM_SANDBOX_STORAGE = ".conan/$EPM_PROFILE/$EPM_SCHEME"    
    .epm/$EPM_PROFILE@$EPM_SCHEME/sandbox/['test_package']
    
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc6d', 'gcc6']
      EPM_SCHEME: ['static', 'shared']


    # =========================================
    # gcc7 x86_64 test
    # =========================================
zlib:@build:
  stage: build
  tags:
  - Linux
  - runner
  - docker
  - workbench:oss-0.2
  image: edgetoolkit/ubuntu:xenial
  dependencies:
  - zlib:gcc7@build
  script:
    cd zlib
    export EPM_SANDBOX_STORAGE = ".conan/$EPM_PROFILE/$EPM_SCHEME"    
    .epm/$EPM_PROFILE@$EPM_SCHEME/sandbox/['test_package']
    
  parallel:
    matrix:
    - EPM_PROFILE: ['gcc7', 'gcc7d']
      EPM_SCHEME: ['static', 'shared']

    # =================================
    # Deploy to conan repo
    # =================================
zlib@deploy:
  stage: deploy
  tags:
  - conan
  - deployer
  - workbench:oss-0.2
  dependencies:
  - zlib:gcc7-armv7@build
  - zlib:gcc6-armv8@build
  - zlib:gcc7-armv8@build
  - zlib:gcc5-armv7@build
  - zlib:gcc5@build
  - zlib:gcc5-armv8@build
  - zlib:gcc6-armv7@build
  - zlib:gcc6@build
  - zlib:MSVC@build
  - zlib:gcc7@build
  script: |
    set -e
    cd zlib
    PROFILES=(
      gcc7-armv7 gcc7-armv7d
      gcc6-armv8d gcc6-armv8
      gcc7-armv8d gcc7-armv8
      gcc5-armv7d gcc5-armv7
      gcc5d gcc5
      gcc5-armv8 gcc5-armv8d
      gcc6-armv7 gcc6-armv7d
      gcc6d gcc6
      vs2019 vs2019d
      gcc7 gcc7d
    )

    for profile in $PROFILES
    do
      for scheme in static shared
      do
        export EPM_PROFILE=$profile
        export EPM_FPROFILE=$scheme
        echo [zlib] - Upload...  $profile $shcme
        epm upload .conan/$porofile/$scheme
      done
    done 