name: re2c
version: 1.3

build-tools:
  msys2:
     version: 20200517
     if: compiler == 'Visual Studio'

test:
  test_package:
    project: test_package
    build-tools:
      re2c: ${__version__}
