---
#- name: Install python3 on Ubuntu or Debian  
#  become_user: root
#  apt: name=python3 state=latest
#  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: install python3 and pip
  become: true
  apt:    
    state: latest
    name:
    - python3
    - python3-pip
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: take python3 as default
  become: true
  alternatives:
    name: python
    link: /usr/bin/python
    path: /usr/bin/python3

- name: take pip3 as default
  become: yes
  alternatives:
    name: pip
    link: /usr/bin/pip
    path: /usr/bin/pip3    


- name: Config pip index url
  command: python3 -m pip config set global.index-url {{PIP_INDEX_URL}}
  when: PIP_INDEX_URL

- name: Config pip index trust honst

  command: python3 -m pip config set install.trusted-host {{PIP_TRUSTED_HOST}}
  when: PIP_TRUSTED_HOST
