name: bison
version: 3.7.1


dependencies:
    m4: 1.4.18
    automake: 1.16.2  

build-tools:
  msys2: &MSYS2
    version: 20200517
    if: compiler == 'Visual Studio'
  automake: 
    version: 1.16.2
    if: compiler == 'Visual Studio'

    

# =====================================
# Package programs (for test only)
# =====================================
program:
- name: test_package
  location: test_package
  executable: bin/test_package
  build-tools:
    bison: ${__version__}
    msys2: *MSYS2

