name: bison
version: 3.7.1


dependencies:
    m4: 1.4.18
    automake: 1.16.2  

build-tools:
  msys2: &MSYS2
    version: 20200517
    if: compiler == 'Visual Studio'
  automake: 
    version: 1.16.2
    if: compiler == 'Visual Studio'

    

test:
  test_package:
    project: test_package
    program: test_package
    build-tools:
      bison: ${__version__}
      msys2: *MSYS2

