name: bison
version: 3.7.1


program:
- name: test_package
  location: test_package
  executable: bin/test_package
  build-tools:
    bison: ${__version__}

  

build-tools:
  msys2: 
    version: 20190524
    if: compiler == 'Visual Studio'
  automake: 
    version: 1.16.2
    if: compiler == 'Visual Studio'

    
dependencies:
    m4: 1.4.18
    automake: 1.16.2



