---
- name: Config source mirror.
  copy:
    src: "mirrors/ubuntu-{{ansible_distribution_major_version}}-{{ansible_distribution_minor_version}}.sources.list"
    dest: /etc/apt/sources.list
  become: yes
