---
- name: Config source mirror.
  copy:
    src: "mirrors/ubuntu-{{ansible_distribution_major_version}}.sources.list"
    dest: /etc/apt/sources.list
  become: yes
- name: ansible apt with_items
  become: yes
  apt:
    name: "{{item}}"
    update_cache: true
    state: present
    install_recommends: no
  with_items:
  - make
  - build-essential
  - libssl-dev
  - zlib1g-dev
  - libbz2-dev
  - libreadline-dev
  - libsqlite3-dev
  - wget
  - curl
  - llvm
  - libncurses5-dev
  - xz-utils
  - tk-dev
  - libxml2-dev
  - libxmlsec1-dev
  - libffi-dev
  - liblzma-dev


# name: download pyenv
# git:
#   repo:  https://github.com/pyenv/pyenv.git
#   dest: ~/.pyenv
#   #version=release-0.22
# name: install pyenv
# shell: |
#   cd ~/.pyenv && src/configure && make -C src
#   echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
#   echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
#   echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n  eval "$(pyenv init -)"\nfi' >> ~/.bashrc
# name: install python
# shell: |
#   #!/bin/bash
#   source ~/.bashrc
#   v=3.8.6;wget https://npm.taobao.org/mirrors/python/$v/Python-$v.tar.xz -P ~/.pyenv/cache/;pyenv install $v 

    
#- name: download pyenv tarball
#  get_url:
#    url: "{{PYEVN_REPO | default('https://github.com/pyenv/pyenv/archive')}}/v{{PYENV_VERSION}}.tar.gz"
#    dest: "/tmp/v{{PYENV_VERSION}}.tar.gz"
#- name: extract pyenv
#  unarchive:
#    src: "{{PYEVN_REPO | default('https://github.com/pyenv/pyenv/archive')}}/v{{PYENV_VERSION}}.tar.gz"
#    dest: ~/
#    #mode: '0755'
#    remote_src: yes
