name: libiconv
version: 1.16


scheme:
  shared:
    options:
      shared: true
  static:
    options:
      shared: false

sandbox:
   test_package: test_package/bin/test_package

build-tools:
  msys2: 
    version: 20190524
    if: os == Windows

