name: zlib
version: 1.2.11


scheme:
  shared:
    options:
      shared: true

  static:
    options:
      shared: false

test:
  test_package:
    program: test
    project: test_package

program:
- name: test_package
  location: test_package
  executable: bin/test

# CI: 23