name: zlib
version: 1.2.11


scheme:
  shared:
    options:
      shared: true

  static:
    options:
      shared: false

test:
  test_package:
    project: test_package
    program: test

# CI: 23