---
- name: Create gitlab-runner and epm folders
  file:
    path: /home/{{ansible_ssh_user}}/{{item}}
    state: directory
    mode: '0755'
  with_items:
    - .epm
    - .epm/.workbench
    - .gitlabrunner

- name: Download gitlab-runner program to ~/.gitlab-runner
  get_url:
    url: "{{ARCHIVE_REPO_URL}}/gitlab-runner/v{{GITLAB_RUNNER_VERSION}}/binaries/gitlab-runner-linux-amd64"
    dest: /home/{{ansible_ssh_user}}/.gitlab-runner/gitlab-runner
    mode: '0766'

- name: Install gitlab service
  shell: |
    ./gitlab-runner stop
    ./gitlab-runner uninstall

    ./gitlab-runner install -c config.toml --user {{ansible_ssh_user}}
  args:
    chdir: /home/{{ansible_ssh_user}}/.gitlab-runner
  become: yes
#  become_user: "{{ansible_ssh_user}}"
#  become_method: sudo




- name: Download mirror.yml
  get_url:
    url: "{{ARCHIVE_REPO_URL}}/mirror.yml"
    dest: /home/{{ansible_ssh_user}}/.epm/mirror.yml