---
- hosts: builder,runner,deployer
  tasks:
  - name: Generate gitlab-runner config
    gitlab_runner_config:
      config: "{{GITLAB_RUNNER_CONFIG_FILE}}"
      db: "{{GITLAB_RUNNER_REGISTER_DB}}"
      hostname: "{{ansible_ssh_host}}"
      type: "{{group_names}}"
      platform: "{{'Windows' if ansible_connection=='winrm' else 'Linux'}}"
      home: "/home/{{ansible_ssh_user}}"
    delegate_to: localhost
#    with_list: "{{group_names}}"

#  - debug: msg="hostname {{ansible_ssh_host}}  {{item}}"
#    with_list: "{{group_names}}"
