- hosts: artifactory
  vars:
    - COMMAND: install
  roles:
  - role: artifactory
    when:
    - target == "artifactory"
#    - inventory_hostname in groups['artifactory']

- hosts: gitlab
  vars:
    - COMMAND: install
  roles:
  - role: gitlab
    when:
    - target == "gitlab"

- hosts: gitlab_runner
  vars:
    - COMMAND: install
  roles:
  - role: gitlab-runner
    when:
    - target == "gitlab-runner"
#    - inventory_hostname in groups['gitlab']

