#!/bin/bash
__dir__=$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)
__top__=$(cd "$__dir__/.."; pwd)

cd $__dir__

ansible-playbook -i ~/.edgetoolkit/config/hosts -e ansible_python_interpreter=/usr/bin/python3 $*
